### ISSUE TITLE
groupby: dates treated as integers rather than strings

### ISSUE THREAD

**Issue by phhu** [opensource9ja/danfojs#100]
If I try grouping on a string column which represents a date (e.g. in ISO format ,e.g. "2021-02-01T06:00:00Z"), the date column is treated as an integer and truncated to the year only ("2021"). 

See the example below, where the `date` column of the third table would be expected I think to contain the full ISO date strings as above, and the ctype of the same column should be `string`, as it is in the original data, rather than `int32`, as in the fourth table.

If I prepend a string-like character to the dates - e.g. "_2021-02-01T06:00:00Z" - I get the expected groupby behaviour.

```js
const dfd = require("danfojs-node")    //version 0.2.0

obj_data = {'date': ["2021-02-01T06:00:00Z","2021-02-01T06:00:00Z","2021-02-02T06:00:00Z","2021-02-02T06:00:00Z"],
            'B': ["bval1", "bval2", "bval3", "bval4"],
            'D': [1.2, 3.45, 60.1, 45],
            }

df = new dfd.DataFrame(obj_data)
df.print()
df.ctypes.print() 

g = df.groupby(["date"]).agg({"D":"sum"})
g.print()
g.ctypes.print() 
```
```
╔═══╤═══════════════════╤═══════════════════╤═══════════════════╗
║   │ date              │ B                 │ D                 ║
╟───┼───────────────────┼───────────────────┼───────────────────╢
║ 0 │ 2021-02-01T06...  │ bval1             │ 1.2               ║
╟───┼───────────────────┼───────────────────┼───────────────────╢
║ 1 │ 2021-02-01T06...  │ bval2             │ 3.45              ║
╟───┼───────────────────┼───────────────────┼───────────────────╢
║ 2 │ 2021-02-02T06...  │ bval3             │ 60.1              ║
╟───┼───────────────────┼───────────────────┼───────────────────╢
║ 3 │ 2021-02-02T06...  │ bval4             │ 45                ║
╚═══╧═══════════════════╧═══════════════════╧═══════════════════╝

╔══════╤══════════════════════╗
║      │ 0                    ║
╟──────┼──────────────────────╢
║ date │ string               ║
╟──────┼──────────────────────╢
║ B    │ string               ║
╟──────┼──────────────────────╢
║ D    │ float32              ║
╚══════╧══════════════════════╝

╔═══╤═══════════════════╤═══════════════════╗
║   │ date              │ D_sum             ║
╟───┼───────────────────┼───────────────────╢
║ 0 │ 2021              │ 4.65              ║
╟───┼───────────────────┼───────────────────╢
║ 1 │ 2021              │ 105.1             ║
╚═══╧═══════════════════╧═══════════════════╝

╔═══════╤══════════════════════╗
║       │ 0                    ║
╟───────┼──────────────────────╢
║ date  │ int32                ║
╟───────┼──────────────────────╢
║ D_sum │ float32              ║
╚═══════╧══════════════════════╝
```

**Comment by phhu** [comment]
This can be worked around by converting the dates to UNIX timestamps (and so int32 cType)

Something like this works:

```js
getTimestamp = dateStr => (+(new Date(dateStr))
```

**Comment by steveoni** [comment]
@phhu  you might need to convert date columns to DateTime column using `df['date'].dt` and then extract your month, day and the likes see issue #95

**Comment by phhu** [comment]
Thanks. From memory, it wasn't particularly convenient to convert the ISO dates to separate year / month /day columns, as the ISO format was easier to handle downstream. The point I was trying to make is that the column should be treated as a string rather than an number (integer), because it is a string (or, at least, I should be able to override the default handling as an integer). ISO date format is useful because it sorts alphabetically in date order when handled as a string, and doesn't need particular handling.
