### ISSUE TITLE
DataFrame.add doesn't respect column and row indices

### ISSUE THREAD

**Issue by phhu** [opensource9ja/danfojs#101]
If I use `DataFrame.add` to add two dataframes together, the order of the rows and columns seems to be used to combine the values, rather than the column and row indices.

E.g. in the below, I think I would expect to see 4 + 20 = 24 for the Col1, r2 sum. Instead the output DataFrame does not have indices, and the sums go by column and row order.

```js
const dfd = require("danfojs-node")     // version 0.2.0

let data = {"Col1": [1, 4, 5, 0], 
            "Col2": [2, 0, 1, 4]}
            
let data2 = {"Col2": [1, 5, 20, 10],    //note swapped column names
             "Col1": [20, 2, 1, 2]}

let df = new dfd.DataFrame(data,{index: ["r1", "r2", "r3", "r4"]})
let df2 = new dfd.DataFrame(data2,{index: [ "r2", "r3", "r4","r5"]})   // note offset index

df.print()
df2.print()

let df_new = df.add(df2)

df_new.print()
```
```
╔════╤═══════════════════╤═══════════════════╗
║    │ Col1              │ Col2              ║
╟────┼───────────────────┼───────────────────╢
║ r1 │ 1                 │ 2                 ║
╟────┼───────────────────┼───────────────────╢
║ r2 │ 4                 │ 0                 ║
╟────┼───────────────────┼───────────────────╢
║ r3 │ 5                 │ 1                 ║
╟────┼───────────────────┼───────────────────╢
║ r4 │ 0                 │ 4                 ║
╚════╧═══════════════════╧═══════════════════╝

╔════╤═══════════════════╤═══════════════════╗
║    │ Col2              │ Col1              ║
╟────┼───────────────────┼───────────────────╢
║ r2 │ 1                 │ 20                ║
╟────┼───────────────────┼───────────────────╢
║ r3 │ 5                 │ 2                 ║
╟────┼───────────────────┼───────────────────╢
║ r4 │ 20                │ 1                 ║
╟────┼───────────────────┼───────────────────╢
║ r5 │ 10                │ 2                 ║
╚════╧═══════════════════╧═══════════════════╝

╔═══╤═══════════════════╤═══════════════════╗
║   │ Col1              │ Col2              ║
╟───┼───────────────────┼───────────────────╢
║ 0 │ 2                 │ 22                ║
╟───┼───────────────────┼───────────────────╢
║ 1 │ 9                 │ 2                 ║
╟───┼───────────────────┼───────────────────╢
║ 2 │ 25                │ 2                 ║
╟───┼───────────────────┼───────────────────╢
║ 3 │ 10                │ 6                 ║
╚═══╧═══════════════════╧═══════════════════╝
```

**Comment by cimm** [comment]
I am new to Danfo (and Pandas for that matter) so not sure if this is related but I have the same when adding JSON.

```js
myjson = [
  { "A": 1, "B": 10 },
  { "A": 2, "B": 20 },
  { "B": 30, "A": 3 },
  { "A": 4, "B": 40 }
]
df = new dfd.DataFrame(myjson)
df.print()
```

```
╔═══╤═══════════════════╤═══════════════════╗
║   │ A                 │ B                 ║
╟───┼───────────────────┼───────────────────╢
║ 0 │ 1                 │ 10                ║
╟───┼───────────────────┼───────────────────╢
║ 1 │ 2                 │ 20                ║
╟───┼───────────────────┼───────────────────╢
║ 2 │ 30                │ 3                 ║
╟───┼───────────────────┼───────────────────╢
║ 3 │ 4                 │ 40                ║
╚═══╧═══════════════════╧═══════════════════╝
```

Not row 2 is swapped. Danfo simply takes the order of the column, not knowing it's reading JSON where the position doesn't matter.

**Comment by steveoni** [comment]
@phhu the current implementation for element-wise operation such as `add, min, div` e.t.c assumes that both data frame have same numbers of rows and probably their index is the same, which makes it easier to prevent using for loop and make use of Tensor flow ops

To fix this, we need to check if they contain the same index, if not we don't use the tensorflow ops (if you will like to help fix this) https://github.com/opensource9ja/danfojs/blob/364c82ad5f70db3fc5b76ce1332d2dc287fe429f/danfojs/src/core/frame.js#L308

**Comment by risenW** [comment]
> I am new to Danfo (and Pandas for that matter) so not sure if this is related but I have the same when adding JSON.
> 
> ```js
> myjson = [
>   { "A": 1, "B": 10 },
>   { "A": 2, "B": 20 },
>   { "B": 30, "A": 3 },
>   { "A": 4, "B": 40 }
> ]
> df = new dfd.DataFrame(myjson)
> df.print()
> ```
> 
> ```
> ╔═══╤═══════════════════╤═══════════════════╗
> ║   │ A                 │ B                 ║
> ╟───┼───────────────────┼───────────────────╢
> ║ 0 │ 1                 │ 10                ║
> ╟───┼───────────────────┼───────────────────╢
> ║ 1 │ 2                 │ 20                ║
> ╟───┼───────────────────┼───────────────────╢
> ║ 2 │ 30                │ 3                 ║
> ╟───┼───────────────────┼───────────────────╢
> ║ 3 │ 4                 │ 40                ║
> ╚═══╧═══════════════════╧═══════════════════╝
> ```
> 
> Note row 2 is swapped. Danfo simply takes the order of the column, not knowing it's reading JSON where the position doesn't matter.

Thanks for sharing this, I do think its a separate issue though.

**Comment by risenW** [comment]
> @phhu the current implementation for element-wise operation such as `add, min, div` e.t.c assumes that both data frame have same numbers of rows and probably their index is the same, which makes it easier to prevent using for loop and make use of Tensor flow ops
> 
> To fix this, we need to check if they contain the same index, if not we don't use the tensorflow ops (if you will like to help fix this)
> 
> https://github.com/opensource9ja/danfojs/blob/364c82ad5f70db3fc5b76ce1332d2dc287fe429f/danfojs/src/core/frame.js#L308

Also, there might be some speed tradeoffs as well
