### ISSUE TITLE
ColData Tensor is not updated after manipulation

### ISSUE THREAD

**Issue by mjarmoc** [opensource9ja/danfojs#104]
Steps to reproduce:
1. Create a new dataframe with 3 columns and 10 rows.
2. Add 1 new column with 10 values.

Expected Result:
col_data_tensor.shape should be `[4,10]`

Actual result:
 col_data_tensor.shape is `[3,10]`

Same applies for dropping columns.

**Comment by steveoni** [comment]
@mjarmoc thanks for pointing this out, I just scheck this out and also see that `df.shape` after `addColumn` is not outputing the updated shape.

Are you working on this already?
