### ISSUE TITLE
Feature Request: Specify columns to show when using table function

### ISSUE THREAD

**Issue by sagoncalves** [opensource9ja/danfojs#105]
Hi i think this can be useful for many reasons. Thanks!!

**Comment by risenW** [comment]
@sagoncalves Thanks for raising this, can you use the feature request template, so we can better understand this request. To be clear, we need some examples of code and result.

**Comment by sagoncalves** [comment]
@risenW Thank you. 

I think it would be nice to choose wich columns of the dataframe you want to plot as a table.

Example of desired use:
``` javascript
    let columnsArr =  ["column_name","another_column_name"];
    df.plot("plot_div").table(columnsArr);
```
If the column param is undefined it will work as always.

I thought maybe this is already possible so also tried doing this but it doesnt works: 
```javascript
    let columnsArr =  ["column_name","another_column_name"];
    let config = {header: { values: columnsArr}}
    df.plot("plot_div").table(config);
```

If you think it would be usefull or not, i'll be more than honoured to contribute in this project, with this or any other issue.
Just let me know :)
