### ISSUE TITLE
Messing with TFJS somehow

### ISSUE THREAD

**Issue by GantMan** [opensource9ja/danfojs#108]
I can't seem to figure this one out.   The version of Danfo that I include makes or breaks TFJS code.

I've created a reproduction of this here: https://github.com/GantMan/danfo-upgrade-issue

The README.md explains everything.

**WARNING:** this demo is from my book and load 700+MB CSV files.   It's kinda slow as hell.  I wish I could have made a smaller reproduction for you, but I figured I'd share the exact example from my book so it's clear EXACTLY how these two bugs affect the user.

To recreate the issue just uncomment or comment the versions at the body tag.
![image](https://user-images.githubusercontent.com/997157/107127876-c2e6b680-687e-11eb-8d8a-8c6c0bc3c5fb.png)

**Comment by risenW** [comment]
@GantMan The latest version `v0.2.2` now exposes tensorflow, so as to fix this error. Can you install and try it out: 

```html
<script src="https://cdn.jsdelivr.net/npm/danfojs@0.2.2/lib/bundle.min.js"></script>
```
