### ISSUE TITLE
plotting value_count of categorical variables as a bar chart not working properly

### ISSUE THREAD

**Issue by sagoncalves** [opensource9ja/danfojs#111]
Hi when i plot the value_count of a column with catergorical values, like this one that has only 2 values, "increasing" and "decreasing", the result of the plot has both axis as numerical.

<img width="352" alt="Screen Shot 2021-02-08 at 9 41 45 AM" src="https://user-images.githubusercontent.com/63732425/107221285-2f35f700-69f2-11eb-82ff-d521dc21be08.png">

Thanks!

**Comment by risenW** [comment]
@sagoncalves can you share the code example you used?

**Comment by sagoncalves** [comment]
@risenW  sure sorry for not reporting it the right way first.

CDN: `https://cdn.jsdelivr.net/npm/danfojs@0.2.2/lib/bundle.min.js`

```javascript
let get = async ()=>{
    let df = await dfd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv");
    let value_count = df["direction"].value_counts();      
    value_count.plot("#div").bar();
} 
```
