### ISSUE TITLE
df.corr() - Undefined function

### ISSUE THREAD

**Issue by sagoncalves** [opensource9ja/danfojs#115]
<img width="567" alt="Screen Shot 2021-02-15 at 1 59 17 PM" src="https://user-images.githubusercontent.com/63732425/107974902-07b4d080-6f96-11eb-8b29-86ea66dcfa50.png">

**Comment by risenW** [comment]
@sagoncalves we do not have the corr function implemented yet.

**Comment by risenW** [comment]
It is a work in progress.. see https://github.com/opensource9ja/danfojs/pull/26

**Comment by sagoncalves** [comment]
@risenW thanks!
