### ISSUE TITLE
How to create new columns based on existing columns? 

### ISSUE THREAD

**Issue by drixie** [opensource9ja/danfojs#117]
In pandas, you can do something like this: 

` df["20sma"] = df["Close"].rolling(window=20).mean()`

How can I use dance to do something similar in which the computed column is added to the same dataframe? 

Also, danfo does not give helpful error messages. It just fails quietly whenever it cannot handle any instruction. Is there a "verbose=true" setting anywhere?

**Comment by risenW** [comment]
To add new columns, you can use the addColumns function. Take a look at the doc here (https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.addcolumn)

Regarding error, we'll definitely work to improve it, as of now, there's no verbose option.
