### ISSUE TITLE
left merge problem

### ISSUE THREAD

**Issue by wodefey** [opensource9ja/danfojs#118]
I am having a problem with left merge if the number of rows in the left table exceeds the number of rows in the right

	const data1 = [
		{year: 2019, color: "red"}, 
		{year: 2020, color: "blue"},
		{year: 2021, color: "green"}
	]
	let df1 = new dfd.DataFrame(data1)
	log.info(df1.print())

	const data2 = [
		{"year": 2018, "month": 1, "sold": 1},
		{"year": 2019, "month": 7, "sold": 7},
		{"year": 2020, "month": 5, "sold": 5}
	]
	let df2 = new dfd.DataFrame(data2)
	log.info(df2.print())

	let df_merged = dfd.merge({ left: df1, right: df2, 
		on: ["year"], how: "left"})
	log.info(df_merged.print())

The above works, wheras:

	const data1 = [
		{year: 2019, color: "red"}, 
		{year: 2020, color: "blue"},
		{year: 2021, color: "green"}
	]
	let df1 = new dfd.DataFrame(data1)
	log.info(df1.print())

	const data2 = [
		{"year": 2018, "month": 1, "sold": 1},
		{"year": 2019, "month": 7, "sold": 7},
	]
	let df2 = new dfd.DataFrame(data2)
	log.info(df2.print())

	let df_merged = dfd.merge({ left: df1, right: df2, 
		on: ["year"], how: "left"})
	log.info(df_merged.print())

The above does not with error message Cannot read property '0' of undefined

**Comment by steveoni** [comment]
@wodefey i will look into this

**Comment by steveoni** [comment]
@wodefey I couldn't reproduce this error; from my end, the second case seems to work

![Screen Shot 2021-03-08 at 09 19 13](https://user-images.githubusercontent.com/20904032/110300917-6a2a4b00-7fef-11eb-8ebf-93fecfc4d69d.png)
