### ISSUE TITLE
How to assign value at specfiic cell?

### ISSUE THREAD

**Issue by ninjakx** [opensource9ja/danfojs#127]
I can access the values at a specifc cell but how to replace them?

`df.loc({ rows: ["0:1"], columns: ["type"] }).data`

**Output:**

```
Array(2) [
  0: Array(1) ["white"]
  1: Array(1) ["white"]
]
```

How to change the value white to black?

**Comment by risenW** [comment]
@ninjakx you can use the replace method to change values in a particular cells. Take a look at the docs https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.replace

**Comment by ninjakx** [comment]
> @ninjakx you can use the replace method to change values in a particular cells. Take a look at the docs https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.replace

But how to assign using particular index and. Col?
This will use a column and match the given value but won't use index

**Comment by scls19fr** [comment]
I was looking for such a feature also!
