### ISSUE TITLE
Danfojs not working with Vue(v2)

### ISSUE THREAD

**Issue by Gregory-Han** [opensource9ja/danfojs#128]
Hi, Team

When I try using Vue(V2) and danfojs.
I allways get the error 
"Module parse failed: Unexpected token (17:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { Str } from "./core/strings";
| export { Utils } from "./core/utils";
> export * as tf from "@tensorflow/tfjs";
| 
| export const _version = "0.2.2";"
 when trying to import danfojs.

Does anybody know where the Problem is or what I can do to fix this?

`<template>
  <div>
    <h1>Pandas</h1>
    <pre>{{ df.head().print() }}</pre>
  </div>
</template>

<script>
import * as df from  'danfojs/danfojs/src/index';

export default {
  name: 'Pandas',
  data() {
    return {
      df: []
    };
  },
  created() {
    this.df = new df.DataFrame(
      { pig: [20, 18, 489, 675, 1776], horse: [4, 25, 281, 600, 1900] },
      { index: [1990, 1997, 2003, 2009, 2014] }
    );
  },
}
</script>"`

**Comment by risenW** [comment]
I'll look into this, but just to confirm, have you tried this: https://danfo.jsdata.org/examples/using-danfojs-in-react

**Comment by gaw89** [comment]
I have the same issue.  If I change [this line](https://github.com/opensource9ja/danfojs/blob/ae1ede30fac60c6d3c08c8a695bfe85aca45ed31/danfojs-browser/src/index.js#L17) to an import and move it to line 2 then add `export { tf };` on line 18, it appears to work normally.

I am using Vue 2.6.11.

**Comment by andreaminieri** [comment]
Thanks @gaw89, your workaround works for me as well.

I was experiencing the same issue importing danfo.js into a Nuxt.js application based on Vue v2.6.11. 
I installed it with `yarn add danfojs` and imported it in a Component with `import * as dfd from "danfojs/src/index"`

**Comment by Gregory-Han** [comment]
Thank you, Andrea.
 
I am still happen same problems.
 
Thank you.
Greg Han
 


안녕하세요.

 
-----Original Message-----

**Comment by dom-devel** [comment]
Was experiencing the same issue with a gatsby application. 

Fix provided by gaw89 also worked for me.

**Comment by Gregory-Han** [comment]
Thank you everyone.

I fixed it by @gaw89 and especially thank you to @gaw89
