### ISSUE TITLE
Replace substring in a column

### ISSUE THREAD

**Issue by kamaraju10** [opensource9ja/danfojs#130]
I want to write the below code in JS using danfo:

sample data:
![image](https://user-images.githubusercontent.com/27988808/109621048-8bb1af80-7b75-11eb-87b0-cc4f90c39fb2.png)
df['Function'] =  "y=maqsc(right=(_1, _2, _3, _4), mid=0, wrong=[_5], w1=1, w2=0, w3=1)"

rep_chars = 'y=|w1=|_|w2=|w3=|right=|wrong=|mid=|mid =|right =|wrong =|Y='
df['Function'] = df['Function'].str.replace(rep_chars,"")

I tried using df.replace() but it doesn't work here as it is not an exact match. Is there any workaround for this?

**Comment by risenW** [comment]
@kamaraju10 The replace method exposes the JavaScript replace method https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace, as such you should use it exactly how you would use it on a single string. 

Regarding your question, is the `rep_chars = 'y=|w1=|_|w2=|w3=|right=|wrong=|mid=|mid =|right =|wrong =|Y='` a Regex expression?

**Comment by kamaraju10** [comment]
@risenW : Thank you for your reply!
Yes, I want to replace a substring in each and every row of that column. Is there something we can do?

**Comment by risenW** [comment]
> @risenW : Thank you for your reply!
> Yes, I want to replace a substring in each and every row of that column. Is there something we can do?

Can you give a clearer example of the input and the expected output you want. I think your Regex expression might be wrong/incomplete:
For instance:

```javascript
sf = new dfd.Series(["y=maqsc(right=(_1, _2, _3, _4), mid=0, wrong=[_5], w1=1, w2=0, w3=1)"])
rep_chars = /y=|w1=|_|w2=|w3=|right=|wrong=|mid=|mid =|right =|wrong =|Y=/
sf = sf.str.replace(rep_chars,"")
sf.print()
```

<img width="690" alt="Screen Shot 2021-03-03 at 10 36 36 AM" src="https://user-images.githubusercontent.com/29900845/109785377-5d32e380-7c0c-11eb-9f20-544db7707adb.png">

**Comment by kamaraju10** [comment]
Hey Thank you for your reply!
As you suggested I looked into the regex, this is the updated: 
`rep_chars = /y=|w1=|__|w2=|w3=|right=|wrong=|mid=|mid =|right =|wrong =|Y=/gi` 
for series it works fine but I want to do for a column in dataframe,

I have a datafarme and this function is a column of it for example 
`df_data = [{
    'ID': 2004,'Function': "y=maqsc(right=(_1, _2, _3, _4), mid=0, wrong=[_5], w1=1, w2=0, w3=1)"
},{'ID': 2005,'Function': "y=maqsc(right=(_1, _2, _4), mid=0, wrong=[_3], w1=1, w2=2, w3=1)"}]
let test_df = new dfd.DataFrame(df_data);
test_df.print()
`
I want to update the Function column. 
Expected Output:
![image](https://user-images.githubusercontent.com/27988808/109912960-0ef31280-7ce8-11eb-8a7b-6f373ea8150a.png)

I tried using this Is there any work around?

**Comment by risenW** [comment]
@kamaraju10 Sorry for the late reply. In such a case, you can do the following:

```javascript
let df_data = [{ 'ID': 2004,'Function': "y=maqsc(right=(_1, _2, _3, _4), mid=0, wrong=[_5], w1=1, w2=0, w3=1)" },{'ID': 2005,'Function': "y=maqsc(right=(_1, _2, _4), mid=0, wrong=[_3], w1=1, w2=2, w3=1)"}]
let test_df = new dfd.DataFrame(df_data);
let rep_chars = /y=|w1=|__|w2=|w3=|right=|wrong=|mid=|mid =|right =|wrong =|Y=/gi
let updated_function = test_df['Function'].str.replace(rep_chars, "")
test_df.addColumn({column: "updated_function", value: updated_function})
test_df.print()
```

<img width="1088" alt="Screen Shot 2021-03-09 at 2 55 05 PM" src="https://user-images.githubusercontent.com/29900845/110481065-74c80b80-80e7-11eb-90c5-7e7c29353ef1.png">
