### ISSUE TITLE
Date range not working properly

### ISSUE THREAD

**Issue by nicolashedoire** [opensource9ja/danfojs#131]
## For this exemple, use START DATE and END DATE

START DATE :  2009-11-01
END DATE :  2010-10-01

Date format => YYYY-MM-DD

https://danfo.jsdata.org/api-reference/series/series.dt.day

Code like in documentation : 

`let dataDays = new dfd.date_range({"start": startDate, "end":endDate});`
`console.log("### DAYS BETWEEN DATES WITH DANFO DATE RANGE : ", dataDays.length);`

## Code result is bad => 364
-----------------------------------------------------------------------------------------------------------------------------
## expected Result => 335

try with this url => https://www.timeanddate.com/date/durationresult.html?d1=1&m1=11&y1=2009&d2=1&m2=10&y2=2010&ti=on

-----------------------------------------------------------------------------------------------------------------------------

## Proof with date-fns

`const { addDays, addMonths, differenceInDays, differenceInMonths  } = require('date-fns');

const dateRange =  function (startDate, endDate, interval) {
    // D = Days
    if (interval === 'D') {
      const days = differenceInDays(endDate, startDate);
      return [...Array(days+1).keys()].map((i) => addDays(startDate, i));
    }
   // M = Months
    if (interval === 'M') {
      const months = differenceInMonths(endDate, startDate);
      return [...Array(months+1).keys()].map((i) => addMonths(startDate, i));
    }
}

let daysBetweenDates = dateRange(new Date(startDate), new Date(endDate), 'D');
console.log('### DAYS BETWEEN DATES WITH CUSTOM DATE RANGE :', daysBetweenDates.length);
`

## Code result ok => 335

-----------------------------------------------------------------------------------------------------------------------------

Thank's for your help :-)

**Comment by risenW** [comment]
@nicolashedoire Thanks for raising this, we'll definitely look into it.

**Comment by risenW** [comment]
@steveoni What do you think?

**Comment by nicolashedoire** [comment]
> @steveoni What do you think?

Yes it's a good idea ! Dates are always a problem in programming ...

**Comment by steveoni** [comment]
@nicolashedoire  and @risenW I just check the `date_range` now, the method is working okay, the only bug is that it is generating more than the required range; for the example, instead of it ending at `10/1/2010` it ends at `10/29/2010`.

When the index of `10/1/2010`  is checked it gives the same result as @nicolashedoire which is 335

**Comment by steveoni** [comment]
@nicolashedoire issue now fixed in #139
