### ISSUE TITLE
Issues in the documentation - proposed fix included.

### ISSUE THREAD

**Issue by alexjeanderae** [opensource9ja/danfojs#133]
While "getting my feet wet" and getting to know Danfo js, I noticed already a few steps in the documentation that are not correct. Running the code yields errors or different output than the one expected.  At this stage, I am not comfortable with gitbook. 

https://danfo.jsdata.org/getting-started
Sorry no paragraph link on that section. Sorting by values (Defaults to ascending): running the block of code returns an error message.

I assume the correct syntax should be
let data = { "A": [-20, 30, 47.3, NaN] ,
             "B": [34, -4, 5, 6] ,
             "C": [20, 2, 3, 30] }

the output would have one more row. 

https://danfo.jsdata.org/getting-started#selection-by-label
I assume the value should be
let data = { "Name": ["Apples", "Mango", "Banana", "Pear"] ,
            "Count": [21, 5, 30, 10] ,
            "Price": [200, 300, 40, 250] }

There are other issues like this including in the 10 mns of Panda/Danfo js . Let me know if this is helpful. Thanks for the library. I am right now considering using it to prototype a NoSQL workflow pet project of mine.

Cheers!

**Comment by risenW** [comment]
@alexjeanderae Thanks for spotting this. I'll make the updates now. It is helpful. 

Also if you're considering making doc fixes, you can edit the markdown directly [here](https://github.com/opensource9ja/danfojs-doc), and also let me know if you need some help.

**Comment by risenW** [comment]
> I am right now considering using it to prototype a NoSQL workflow pet project of mine.

I'm looking forward to this tool as well. We'd love to feature it in docs
