### ISSUE TITLE
Lack of DataFrame.append()?

### ISSUE THREAD

**Issue by alexwenbj** [opensource9ja/danfojs#15]
Title says all.
BTW:Thank you for this great work!

**Comment by risenW** [comment]
By append do mean to add new rows or columns to the DataFrame? Because we have the [addColumns](https://jsdata.gitbook.io/danfojs/api-reference/dataframe/danfo.dataframe.addcolumn) function already, but non for row yet.

**Comment by alexwenbj** [comment]
Just like the pandas DataFrame.append(),it appends rows of other to the end of caller, returning a new object.

**Comment by risenW** [comment]
Okay, we'll work on it. Thanks

**Comment by risenW** [comment]
Fixed!
