### ISSUE TITLE
Merge function does not throw correct error on more than 2 keys

### ISSUE THREAD

**Issue by risenW** [opensource9ja/danfojs#151]
**Describe the bug**
Danfojs does not throw correct error when more than one key specified in the merge function

**To Reproduce**
1. Go to 'https://playnotebook.jsdata.org/'
2. load danfojs version 0.2.4 using load_packages
3. run the following code:
```javascript
let data = [['K0', 'k0', 'A0', 'B0'], ['k0', 'K1', 'A1', 'B1'],
            ['K1', 'K0', 'A2', 'B2'], ['K2', 'K2', 'A3', 'B3']]

let data2 = [['K0', 'k0', 'C0', 'D0'], ['K1', 'K0', 'C1', 'D1'],
            ['K1', 'K0', 'C2', 'D2'], ['K2', 'K0', 'C3', 'D3']]

let colum1 = ['Key1', 'Key2', 'A', 'B']
let colum2 = ['Key1', 'Key2', 'A', 'D']

let df1 = new dfd.DataFrame(data, { columns: colum1 })
let df2 = new dfd.DataFrame(data2, { columns: colum2 })
merge_df = dfd.merge({ "left": df1, "right": df2, "on": ["Key1", "Key2", "C0"]})
table(merge_df)
```
4. See error:
<img width="826" alt="Screen Shot 2021-03-16 at 9 34 41 AM" src="https://user-images.githubusercontent.com/29900845/111280033-a4bd6480-863b-11eb-9eb4-b102e17a2571.png">

**Expected behavior**
Throw error saying merge function can only accept two keys at a time. 

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by risenW** [comment]
@steveoni Did you finish this?

**Comment by steveoni** [comment]
I checked this: the issue is, `C0` specified in `on` list of keys, is not even a column.
