### ISSUE TITLE
Issue Install danfojs-node 

### ISSUE THREAD

**Issue by AmauryVa** [opensource9ja/danfojs#157]
Hi everyone,
I have issue when i install danfojs-node with npm : 
```
npm WARN deprecated @types/csv-parse@1.2.2: This is a stub types definition. csv-parse provides its own type definitions, so you do not need this installed.
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path C:\Users\**\Desktop\NodeJS Developpement\Mysql JS\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.2.0.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings
npm ERR! symlink ./lib/napi-v8 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v8
npm ERR!   * Symlink of lib\napi-v8\tensorflow.dll failed, creating a copy on disk.
npm ERR! node:internal/process/promises:245
npm ERR!           triggerUncaughtException(err, true /* fromPromise */);
npm ERR!           ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, copyfile 'C:\Users\**\Desktop\NodeJS Developpement\Mysql JS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'C:\Users\**\Desktop\NodeJS Developpement\Mysql JS\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tensorflow.dll'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'copyfile',
npm ERR!   path: 'C:\\Users\\**\\Desktop\\NodeJS Developpement\\Mysql JS\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
npm ERR!   dest: 'C:\\Users\\**\\Desktop\\NodeJS Developpement\\Mysql JS\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8\\tensorflow.dll'
npm ERR! }
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR!     at ChildProcess.emit (node:events:369:20)
npm ERR!     at maybeClose (node:internal/child_process:1067:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
npm ERR!   killed: false,
npm ERR!   code: 1,
npm ERR!   signal: null,
npm ERR!   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v8'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\**\AppData\Local\npm-cache\_logs\2021-03-27T00_12_51_686Z-debug.log
```

The problem come from tensorflow and i have no idea to solve it.
Thank you

**Comment by ninjakx** [comment]
does this helps: https://stackoverflow.com/questions/66402003/sysmlink-error-when-installing-tensorflow-tfjs-node?

**Comment by risenW** [comment]
@AmauryVa Try installing the latest danfo-node v0.2.6.

**Comment by AmauryVa** [comment]
@ninjakx Thank you for the link. I had to try 2 times to make it work.
@risenW Ok, i will try to install this version.

**Comment by sinayra** [comment]
@AmauryVa How did you manage to solve this? I tried @ninjakx and @risenW suggestions, but I still keep getting the same error.

**Comment by risenW** [comment]
> @AmauryVa How did you manage to solve this? I tried @ninjakx and @risenW suggestions, but I still keep getting the same error.

Did you try installing the latest version?

**Comment by sinayra** [comment]
> 
> 
> > @AmauryVa How did you manage to solve this? I tried @ninjakx and @risenW suggestions, but I still keep getting the same error.
> 
> Did you try installing the latest version?

Yes, I did.

**Comment by risenW** [comment]
This is looking like a tensorflow install error. Do you have an existing tfjs-node version installed before? Maybe remove and do a clean installation. 

If that doesn't work try installing @tensorflow/tfjs-node": "3.3.0 separately first.

**Comment by sinayra** [comment]
> 
> 
> This is looking like a tensorflow install error. Do you have an existing tfjs-node version installed before? Maybe remove and do a clean installation.
> 
> If that doesn't work try installing @tensorflow/tfjs-node": "3.3.0 separately first.

I tried without installing tfjs-node package, just a pure `npm install danfojs-node`. It didn't worked, so I tried to install the latest tfjs-node and, yes, same thing.
However, I didn't tried the 3.3.0 version, only the 3.4.0. I'll try this one and hope for the best.

**Comment by sinayra** [comment]
Just for future reference, I've downgraded my node to 12.18.0 version, deleted node_modules, removed the @tensorflow/tfjs-node from dependencies and run once again the `npm install danfojs-node` command. Everything working just fine now.

**Comment by MashhourAbbas** [comment]
its not working... can tell me again what have you done?

**Comment by codeinhere123** [comment]
hi is there any update on this issue? trying to install danfo but still stuck in the same issue

**Comment by codeinhere123** [comment]
i tried to downgrade to 12.18.0 version, deleted node_modeles, removed tensorflow/tfjs-node dependency from package and package.lock file and run again `npm install danfojs-node` command. it still have the same issue. i also tried to install danfo-node v0.2.6 but it still have the issue.

**Comment by steveoni** [comment]
@codeinhere123 are you using macos ?

**Comment by sabirnc** [comment]
i also facing the same issue
