### ISSUE TITLE
Please update dependencies to fix Axios security issue

### ISSUE THREAD

**Issue by radekBednarik** [opensource9ja/danfojs#161]
After installing npm warns of security issue.

`npm audit` reports:

> # npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
fix available via `npm audit fix`
node_modules/axios
  tableschema  <=1.12.3
  Depends on vulnerable versions of axios
  node_modules/tableschema
    frictionless.js  *
    Depends on vulnerable versions of tableschema
    node_modules/frictionless.js
      danfojs-node  >=0.1.6
      Depends on vulnerable versions of frictionless.js
      node_modules/danfojs-node

`npm audit fix` is not able to fix this.

Are you able to fix this on your side?

Also, thank you for this awesome package!

**Comment by risenW** [comment]
Thanks for spotting this, I’ll fix it ASAP.

**Comment by risenW** [comment]
Fixed!
