### ISSUE TITLE
Filter function that supports both boolean mask and multiple logical operators 

### ISSUE THREAD

**Issue by risenW** [opensource9ja/danfojs#180]
We need a filter function that can accept multiple logical operators and also be able to filter by a boolean mask, just like pandas as shown here. There are numerous use cases of this, and we certainly have to implement it.

See discussion https://github.com/opensource9ja/danfojs/discussions/170 and https://github.com/opensource9ja/danfojs/discussions/179

## Acceptance
* [x] We can filter a DataFrame or Series by using a boolean mask as demonstrated in [this pandas question](https://stackoverflow.com/questions/37362984/select-from-pandas-dataframe-using-boolean-series-array) **Done** in #235 
* [x] We can query with multiple logical operators

**Comment by undefined-ask** [comment]
Are you working on it? I'm interested in this issue

**Comment by risenW** [comment]
> Are you working on it? I'm interested in this issue

That would be great. Thanks for the offer. At the moment, I'm doing some base refactoring to Typescript- see #235 
So I'll ask you to hold on till I'm done, so you can implement this new update there.

**Comment by risenW** [comment]
Fixed in #235
