### ISSUE TITLE
Another sorting error

### ISSUE THREAD

**Issue by franz101** [opensource9ja/danfojs#182]
When sorting str date values the order won't change.
For example I had the following index:
[new Date(2020,4,1).toJSON(),new Date(2020,4,3).toJSON(),new Date(2020,4,2).toJSON(),new Date(2020,4,10).toJSON()]

Any idea? I used 0.2.5 (or the latest released version). Cheers. Great project.

**Comment by steveoni** [comment]
@franz101 can you give more insight in order to reproduce the same error
