### ISSUE TITLE
query operation "not equal"

### ISSUE THREAD

**Issue by Machuntox** [opensource9ja/danfojs#184]
I would like to select all rows, which dont have specific values in a column. Therefor a query option for not equal "!=" would be very helpful.

thanks in advance.

**Comment by steveoni** [comment]
this query option already exist

**Comment by Machuntox** [comment]
ah, I'm sorry. Apparently it isn't written in the docs = https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.query
