### ISSUE TITLE
Mean aggregation with NaN excluded

### ISSUE THREAD

**Issue by tonyabracadabra** [opensource9ja/danfojs#187]
I tried doing aggregation on a column with NaN in it and it got me this error, is there a way we can excluding the NaNs when we are doing mean aggregation? Or is there a way we can define our own aggregation functions?

```
Error: The new shape (NaN,0) has NaN elements and the old shape (0) has 0 elements. The new shape and old shape must have the same number of elements.
```

**Comment by risenW** [comment]
@tonyabracadabra Can you provide more details, like an example code.

**Comment by steveoni** [comment]
@tonyabracadabra is this mean aggregation on `groupby` data if so you can use `.apply` to create a custom aggregation`
