### ISSUE TITLE
Read config value from x variable instead of y

### ISSUE THREAD

**Issue by risenW** [opensource9ja/danfojs#188]
Change `this_config["y"]` to ` this_config["x"]`
https://github.com/opensource9ja/danfojs/blob/e15aff19a58598d8f3e6da14426b594219418146/danfojs-browser/src/plotting/plot.js#L414

**Comment by adithyaakrishna** [comment]
@risenW Can I work on this?

**Comment by risenW** [comment]
> @risenW Can I work on this?

Yes please go ahead. Thanks 😊
