### ISSUE TITLE
Issue on .sort_values

### ISSUE THREAD

**Issue by chris-sel** [opensource9ja/danfojs#192]
**Describe the bug**
Getting back the same dataframe when attempting to df.sort_values (when keeping the date&time input as a column) or df.sort_index (when setting it as the index). Examined dataframe comes from uploaded timeseries data .csv file, which is parsed using PapaParse. dateSeries = df[df.column_names[0]].dt works fine.

Date & Time format example: 2019-05-29 13:44:00.000

**To Reproduce**
(1. Fetch local timeseries csv data using FileReader API
2. Parse to JS object (array of objects) using PapaParse)
3. Create a df = new dfd.DataFrame(parsed.data)
4. dateSeries = df[df.column_names[0]].dt;
5. Attempt to df.sort_values({by: df.column_names[0], inplace: true}) or df.set_index({ key: df.column_names[0], inplace: true })
df.sort_index({inplace: true});
6. See unchanged dataframe

**Expected behavior**
Expected sorting of the dataframe by the entry date of each input.

**Desktop:**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Firefox
 - Version: 87.0

**Comment by steveoni** [comment]
@chris-sel if you are trying to parse uploaded file to danfojs can you check this out https://github.com/opensource9ja/Data-aRT/blob/master/src/App.js

If this is not what you want, can you paste a code example to fully replicate this error

**Comment by risenW** [comment]
Closing this as it looks stale
