### ISSUE TITLE
to_json() output is a string

### ISSUE THREAD

**Issue by spleshakov** [opensource9ja/danfojs#195]
1. Code example from https://danfo.jsdata.org/api-reference/dataframe/dataframe.to_json is not working, as there is an extra (fourth) value in "Count" column
 
2. Taking code example from https://danfo.jsdata.org/api-reference/dataframe/dataframe.to_json, correcting json data and adding `console.log(typeof json)` as follows

```
const dfd = require("danfojs-node")

let data = { "Abs": [20.2, 30, 47.3] ,
	"Count": [34, 4, 5] ,
	"country code": ["NG", "FR", "GH"] }

let df = new dfd.DataFrame(data)

df.to_json("/Users/spleshakov/Library/Application Support/JetBrains/WebStorm2021.1/scratches/path.csv").then((json) => {
	console.log(json);
	console.log(typeof json)
}).catch((err) => {
	console.log(err);
})
```
results in this output
```
[{"Abs":20.2,"Count":34,"country code":"NG"},{"Abs":30,"Count":4,"country code":"FR"},{"Abs":47.3,"Count":5,"country code":"GH"}]
string
```
Expected type of retuned value is json-like Object

**Comment by Tunjii10** [comment]
The  source code uses Json_stringify to convert dataframe to JSON and it works. Using typeof on a stringified object returns String data type.
Here is a link for better understanding https://javascript.info/json.
