### ISSUE TITLE
Support ObservableHQ

### ISSUE THREAD

**Issue by kalebpace** [opensource9ja/danfojs#197]
**Is your feature request related to a problem? Please describe.**
Cannot import danfo into an ObservableHQ notebook. I have seen forum posts where people seem to have danfo working in a notebook, but there are no official examples and the methods of importing I have tried do not work. 

![image](https://user-images.githubusercontent.com/5586615/117187580-ae448c80-ada1-11eb-8e14-28015ae9ec5a.png)

**Describe the solution you'd like**
Would like to run `dfd = require('danfojs@0.2.5')` to provide dataframes to the notebook

**Describe alternatives you've considered**
- Tried uploading and importing minified bundle to a notebook
- Tried requiring a direct unpkg/jsdelivr link

**UPDATE**
It figures I would find a code snippet shortly after creating this issue. Below imports danfo, maybe add to official guide? 

![image](https://user-images.githubusercontent.com/5586615/117188537-c668db80-ada2-11eb-9ec3-92e23281728a.png)

**Comment by steveoni** [comment]
@kalebpace sorry for the late reply. Here are some materials that could help:
https://observablehq.com/@visnup/hello-danfo-js
https://heartbeat.fritz.ai/end-to-end-machine-learning-in-javascript-using-danfo-js-and-tensorflow-js-part-1-223223c83935

**Comment by selenecodes** [comment]
For people wondering how to get it to work on version 1.0.3 change the path to the `lib/bundle.js` file like so:
```javascript
dfd = require("danfojs@1.0.3/lib/bundle.js").catch(() => {
  window.dfd.Series.prototype.print = window.dfd.DataFrame.prototype.print = function () {
    return print(this);
  };
  return window.dfd;
})
```

**Comment by risenW** [comment]
> For people wondering how to get it to work on version 1.0.3 change the path to the `lib/bundle.js` file like so:
> 
> ```js
> dfd = require("danfojs@1.0.3/lib/bundle.js").catch(() => {
>   window.dfd.Series.prototype.print = window.dfd.DataFrame.prototype.print = function () {
>     return print(this);
>   };
>   return window.dfd;
> })
> ```

Thanks for sharing @selenecodes In case anyone is interested, I have put together a starter Observable notebook: https://observablehq.com/@risingodegua/using-danfojs-on-observablehq
