### ISSUE TITLE
Incorrect type definition for Dataframe.ctypes

### ISSUE THREAD

**Issue by jpkli** [opensource9ja/danfojs#198]
Docs said Dataframe.ctypes is Series - https://danfo.jsdata.org/api-reference/dataframe/dataframe.dtypes

But type definition is "any []" - https://github.com/opensource9ja/danfojs/blob/master/danfojs-node/types/core/frame.d.ts#L337

It's returning as Series in the source - https://github.com/opensource9ja/danfojs/blob/eb5919d2cac34271fc3b725fa24aa3ad4eacde37/danfojs/src/core/frame.js#L1848

Should the type definition be fixed?

Thank you!

**Comment by risenW** [comment]
FIXED in #211
