### ISSUE TITLE
Weird slicing behaviour

### ISSUE THREAD

**Issue by callmekatootie** [opensource9ja/danfojs#203]
**Describe the bug**

The output after slicing does not match the expectation

**To Reproduce**

```javascript
const dfd = require('danfojs-node')

let data = { "Name": ["Apples", "Mango", "Banana", "Pear"] ,
           "Count": [21, 5, 30, 10] ,
           "Price": [200, 300, 40, 250] }

let df = new dfd.DataFrame(data)

let sub_df = df.iloc({rows: ["2:3"], columns: ["0:1"]})
sub_df.print()
```

The above code gives me the output:

![image](https://user-images.githubusercontent.com/2317133/119234562-3d94c280-bb4c-11eb-9d9d-c3ae9859d789.png)

**Expected behavior**

The output that I get has all the columns. Expected was only the Name column to be shown since I have sliced with `"0:1"` for columns

**Desktop (please complete the following information):**

Ubuntu 20.04

**Comment by steveoni** [comment]
@callmekatootie I will look into it. thanks

**Comment by risenW** [comment]
FIXED: https://github.com/opensource9ja/danfojs/pull/209
