### ISSUE TITLE
Error: File format not supported - when creating dataframe in Node-RED function node

### ISSUE THREAD

**Issue by vinaysudani** [opensource9ja/danfojs#206]
`const dfd = require("danfojs-node");
json_data = [
    { A: 0.4612, B: 4.28283, C: -1.509, D: -1.1352 },
    { A: 0.5112, B: -0.22863, C: -3.39059, D: 1.1632 },
    { A: 0.6911, B: -0.82863, C: -1.5059, D: 2.1352 },
    { A: 0.4692, B: -1.28863, C: 4.5059, D: 4.1632 },
];
df = new dfd.DataFrame(json_data);
df.print();`

This code snippet produces expected result when running with node.js. when running the code with node-red function node it throws an error - "Error: File format not supported".

The issue is described in detail on this thread on the node-red forum.
https://discourse.nodered.org/t/error-while-executing-code-with-function-node/46443

**Comment by vinaysudani** [comment]
A workaround to the issue is also mentioned on the same thread.
https://discourse.nodered.org/t/error-while-executing-code-with-function-node/46443/7?u=vinaysudani

**Comment by risenW** [comment]
Thanks for raising this issue and linking a solution. 

FIXED: https://github.com/opensource9ja/danfojs/pull/208

**Comment by vinaysudani** [comment]
Thanks for looking into it and quickly applying it to the source.
