### ISSUE TITLE
Plotly table not being plotted

### ISSUE THREAD

**Issue by govinda18** [opensource9ja/danfojs#214]
**Describe the bug**
Table with plotly is not getting plotted.

**To Reproduce**
https://codepen.io/govindatotlaisasd/pen/wvJpYxo

**Expected behavior**
https://danfo.jsdata.org/api-reference/plotting/tables - As suggested in this doc

Plots a plot instead.
![image](https://user-images.githubusercontent.com/25079291/120342408-628bf100-c315-11eb-8b99-973a3e96f0e7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Chrome
 - Version: danfojs@0.2.3

**Comment by risenW** [comment]
Hi @govinda18 You should update your Plotly version:
See: https://codepen.io/govindatotlaisasd/pen/wvJpYxo

**Comment by risenW** [comment]
Hi @govinda18 You should update your Plotly version:
See: https://codepen.io/govindatotlaisasd/pen/wvJpYxo
