### ISSUE TITLE
Row's named index may conflict with the slice notation

### ISSUE THREAD

**Issue by gregory-chatelier** [opensource9ja/danfojs#220]
.iloc() accepts a string slice object with ints, e.g. "1:7"

I came across a case where row indices were like the string : "ANN_T1_1:9,100"

In case of multiple indices there is no problem. Good news ;-)

sub_df = df.loc({rows:['2010', '2011'], columns:['TERM_N1_I', 'TERM_N1_3:1']})
sub_df.print()

╔══════╤═══════════════════╤═══════════════════╗
║                │ TERM_N1_I         │ TERM_N1_3:1                                                ║
╟──────┼───────────────────┼───────────────────╢
║       2010 │ 564239               │ 315269                                                          ║
╟──────┼───────────────────┼───────────────────╢
║       2011 │ 604804               │ 315222                                                          ║
╚══════╧═══════════════════╧═══════════════════╝

Now in case of only one index, the slice object notation conflicts with the name of the index !

sub_df = df.loc({rows:['2010', '2011'], columns:['TERM_N1_3:1']})

Error: The number of values should be positive.
    at Au (bundle.min.js:6)
    at e.value (bundle.min.js:6)
    at a (bundle.min.js:6)
    at DataFrame.value (bundle.min.js:6)
    at index.js:75

**Comment by risenW** [comment]
@gregory-chatelier This is a rare edge case because generally when a single column property is passed to the loc function, we generate slices by splitting on `:` character. So in your example (columns:['TERM_N1_3:1']) , the column name contains `:`, and as such the error. 

The quickest and best way to solve this will be to rename your column names.

**Comment by gregory-chatelier** [comment]
This is indeed a very special case, but I rely on external providers for column names.
As a workaround i use integer indices, even if it is less convenient.

What bothers me is the inconsistency of comportment between an array with only one element versus an array of more : this is the source of many potential issues.

Now, try indexing by integers : iloc({columns[10,12]}) works as expected but iloc({columns[12]}) doesn't.
However iloc({columns["12"]}) is all right !
