### ISSUE TITLE
Combining Strings for Grouped Columns

### ISSUE THREAD

**Issue by iliyaML** [opensource9ja/danfojs#221]
**Is your feature request related to a problem? Please describe.**
May I know if this feature is available in danfojs?

**Describe the solution you'd like**
Is there something similar to this? This is a pandas example. https://colab.research.google.com/drive/1l9R1QTixQCHGOFvTjyT9qOnS8DCngi_4?usp=sharing

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/19851002/121740245-64349080-cb2f-11eb-8861-405d758bcd86.png)

**Comment by steveoni** [comment]
@iliyaML sorry for the late reply.
This is possible in Danfojs initially, but with previous `.apply` the value of `x` in your callback function `f(x)` will be a Series value, hence its not possible to access the columns as you specify.

But now the`.apply` is now updated to pass in DataFrame instead of array of Series.

So the above code can be implemented as follow:
```js
let data = [{ 'machine-id': 'c-200', 'category': 'auxiliary', 'title': 'oh god this is a serious issue', 'alert-id': 1 },
    { 'machine-id': 'c-300', 'category': 'performance', 'title': 'another one', 'alert-id': 2 },
    { 'machine-id': 'c-300', 'category': 'performance', 'title': 'please help me', 'alert-id': 3 },
    { 'machine-id': 'c-300', 'category': 'machine', 'title': 'lols', 'alert-id': 4 },
    { 'machine-id': 'c-200', 'category': 'auxiliary', 'title': 'haha', 'alert-id': 5 },
    { 'machine-id': 'c-200', 'category': 'performance', 'title': 'really?', 'alert-id': 6 }];
  let df = new dfd.DataFrame(data);
  function f(x){
    data = {
      count: [x['title'].count()],
      title: [x['title'].values.join("_")],
      alertId: [x['alert-id'].astype('string').values.join("_")]
    };
    return new dfd.DataFrame(data);
  }
  let s = df.groupby(['machine-id', 'category']);

  s.apply((x) => f(x)).print();
```

**Comment by iliyaML** [comment]
@steveoni , thanks for sharing this. However, I tried the code your shared on danfojs version 0.2.7 but it's not working.

Below is a snapshot of the error I'm getting.

![image](https://user-images.githubusercontent.com/19851002/131210274-50257d88-7657-4e99-9d49-82b42051a385.png)
![image](https://user-images.githubusercontent.com/19851002/131210289-90739759-ed79-4b1a-9865-28dad2a40dc8.png)

Was there a breaking change between different versions?

**Comment by steveoni** [comment]
@iliyaML I don't think the pr that fixes this has being added to the new development.

For now you can copy the changes from this pr and add it to your codebase or clone and build from your end.

@risenW
