### ISSUE TITLE
Box plot does not plot columns against index

### ISSUE THREAD

**Issue by risenW** [opensource9ja/danfojs#226]
When a list of columns is specified to the box plots config, it should plot each column against the index. The doc says it's plotting against the index but there's a slight mistake in the code. See the line below:

https://github.com/opensource9ja/danfojs/blob/ae106c4bbfb60d56af8e6ba89a909a79dac86297/danfojs-browser/src/plotting/plot.js#L659

To fix, modify the following [code](https://github.com/opensource9ja/danfojs/blob/ae106c4bbfb60d56af8e6ba89a909a79dac86297/danfojs-browser/src/plotting/plot.js#L659) from :

```javascript
trace["y"] = this.ndframe[c_name].values; 
```

to 

```javascript
trace["x"] = this.ndframe[c_name].values; 
trace["y"] = this.ndframe.index; 
```

**Comment by RhnSharma** [comment]
I would like to take this one.
