### ISSUE TITLE
index based access of elements using .loc on Series

### ISSUE THREAD

**Issue by hemasunder** [opensource9ja/danfojs#229]
we have this for DataFrame [here](https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.loc), but missing for Series.

I just can't find a way to access an element at an index

**Comment by risenW** [comment]
@hemasunder Great request, I'm surprised we didn't add this. I'll fix this.

**Comment by risenW** [comment]
Fixed in #235
