### ISSUE TITLE
Get column values as an array

### ISSUE THREAD

**Issue by iserranoe** [opensource9ja/danfojs#233]
**Is your feature request related to a problem? Please describe.**

Given the example in the documentation:
```
const dfd = require("danfojs-node")

let data = {"A": [-20.1, 30, 47.3, -20],
            "B": [34, -4, 5, 6], 
            "C": [20, -20, 30, -40]}
            
let df = new dfd.DataFrame(data)

console.log(df.values)
```
And the output
```
[
  [ -20.1, 34, 20 ],
  [ 30, -4, -20 ],
  [ 47.3, 5, 30 ],
  [ -20, 6, -40 ]
]
```
It is useful to obtain the values by rows, but I would like to obtain the values by columns, i.e. to recover the original arrays. 

**Describe the solution you'd like**

It'd be great to have something like Pandas: ``df['A'].to_list()`` with output:  ``[-20.1, 30, 47.3, -20]``

**Comment by risenW** [comment]
@iserranoe You can do the following for column as well:
console.log(df["A"].values)
