### ISSUE TITLE
DataFrame.append with column names

### ISSUE THREAD

**Issue by iserranoe** [opensource9ja/danfojs#234]
**Is your feature request related to a problem? Please describe.**

Sorry if this feature is implemented, I couldn't find it in the documentation. When I append a row in a dataframe with column names, the new data is not placed below the previous rows:

```
let datos = {'columna1':[1,2,3],'columna2':[4,5,6]}
let df= new dfd.DataFrame(datos)
df.print()
```
columna1   columna2 
      1               4                   
      2               5         
      3               6  

Options I tried:
`df.append([[3,8]])`
`df.append([[3,8]],columns=["columna1","columna2"])`
`df.append(data=[[3,8]],columns=['columna1','columna2'])`

With the output:
columna1   columna2             0                1
      1               4                    NaN            NaN
      2               5                    NaN            NaN
      3               6                    NaN            NaN
      NaN          NaN                 3                8

Or these options that don't work
`df.append([{'columna1':3,'columna2':8}])`
`df.append(data={'columna1':3,'columna2':8})`
`df.append({'columna1':3,'columna2':8})`
`df.append(data=[3,8],columns=['columna1','columna2'])`

**Describe the solution you'd like**

The output I expect is:
columna1   columna2 
      1               4                   
      2               5         
      3               6  
      3               8

**Comment by steveoni** [comment]
@iserranoe I think i break this in the latest version. I make some updates to `concat` to work perfectly with `groupby` table indexing, and `append` is using the `concat` method. The test should have caught this though

Sorry for this.

If you need this urgently, you can do well to use the previous version.

**Comment by iserranoe** [comment]
@steveoni 

Thank you very much! That's working perfectly

**Comment by risenW** [comment]
@steveoni You may want to open an issue referencing this, so we don't forget to fix it.
