### ISSUE TITLE
errors in groupby.agg in browser mode

### ISSUE THREAD

**Issue by furion4tom** [opensource9ja/danfojs#244]
**Describe the bug**
when i use the example in Getting started : groupby.sum with browser mode ,it turns out to be wrong

**Screenshots**
![image](https://user-images.githubusercontent.com/7701597/126129059-3ee9d3e1-38bb-4af4-a892-45df6bb48d07.png)
![image](https://user-images.githubusercontent.com/7701597/126129139-ebf92e9c-11da-4fa6-ba89-4476ef7f449b.png)

while when i use nodejs to run the same example ,it's all right

**Screenshots**
![image](https://user-images.githubusercontent.com/7701597/126129932-8e2dffa5-ee5f-45d3-908b-523646f01a35.png)

**Desktop (please complete the following information):**
 - OS: [windows7]
 - Browser  chrome]

**Comment by steveoni** [comment]
@furion4tom try using the current version of Danfo.js

**Comment by furion4tom** [comment]
wow,that works! thankyou
