### ISSUE TITLE
can't read excel file within danfo.read_excel in browser model

### ISSUE THREAD

**Issue by furion4tom** [opensource9ja/danfojs#245]
i use the example of dfd.read_excel but ...
**Screenshots**
![image](https://user-images.githubusercontent.com/7701597/126285612-02f661ff-911c-460f-9832-8a1c07ea3db2.png)
here is the source
**Screenshots**
![image](https://user-images.githubusercontent.com/7701597/126285937-83178db4-6daf-4468-ae12-facb62780ced.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 93.0.4557.2

**Additional context**
using https://cdn.jsdelivr.net/npm/danfojs@0.2.7/lib/bundle.min.js

**Comment by steveoni** [comment]
@furion4tom I think is cross-origin access restriction

This is the error I obtained before the one you screenshotted:
```
Access to fetch at 'https://file-example-com.github.io/uploads/2017/02/file_example_XLS_100.xls' from origin 'https://playnotebook.jsdata.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by steveoni** [comment]
> @furion4tom I think is cross-origin access restriction
> 
> This is the error I obtained before the one you screenshotted:
> 
> ```
> Access to fetch at 'https://file-example-com.github.io/uploads/2017/02/file_example_XLS_100.xls' from origin 'https://playnotebook.jsdata.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> ```

@furion4tom i think I did not get the URL right the first time.

I tried it again and it's working okay.
<img width="1257" alt="Screen Shot 2021-07-20 at 09 56 21" src="https://user-images.githubusercontent.com/20904032/126304039-d4b41f22-2c8a-4b3b-87e7-b7d6917e5bd7.png">

**Comment by furion4tom** [comment]
thanks
