### ISSUE TITLE
can't convert excel ton dataframe 

### ISSUE THREAD

**Issue by OscarEcoTree** [opensource9ja/danfojs#246]
<img width="694" alt="code3" src="https://user-images.githubusercontent.com/86836946/126295639-c998aa31-edba-45d2-aefa-c745667fe5cf.png">

Hello, 

I need to  be able to convert an Excel into a dfd.DataFrame. I've been able to read an excel and print it but "df" seems to be a void type and not DataFrame. 

If anyone knows how to do so, please let me know ! 

I also tried to use the already existing "read_excel" function of danfojs-node. However, it doesn't give a DataFrame but a Promise<DataFrame> and I don't know how to convert it. 

Thanks

**Comment by steveoni** [comment]
@OscarEcoTree You are not meant to return `test.head().print()` , it's just like trying to return `console.log()` the return value will be void. The best thing is to return `test.head()`

Btwn When you check your console did you see any output. Also whenever you use `df.head().print()` you don't need to wrap it inside `console.log`

**Comment by OscarEcoTree** [comment]
Hello, @steveoni, thank you for you answer. 
Yes I've got an ouput in the console : 

<img width="905" alt="code4" src="https://user-images.githubusercontent.com/86836946/126306699-01181fba-3cca-41df-b171-8cbcce92dbf9.png">

with this code : 

<img width="693" alt="code5" src="https://user-images.githubusercontent.com/86836946/126306804-1c647305-7eaf-4789-a3b2-c83e03a8d481.png">


However, df is still not a DataFrame type object and I can't use DataFrame functions

**Comment by steveoni** [comment]
@OscarEcoTree  `df.head()` is of type `DataFrame` since you are using `Typescript` we have some Type definition here https://github.com/opensource9ja/danfojs/tree/master/danfojs-browser/types
