### ISSUE TITLE
filter with Multiple conditions request

### ISSUE THREAD

**Issue by jasonwu513** [opensource9ja/danfojs#257]
**Is your feature request related to a problem? Please describe.**

Try to use query method with multiple condition, but fail. only support for single condition filter.

```javascript
        df2 = df.query({
            "column": "result",
            "is": "!=",
            "to": "A"
        })
```

**Describe the solution you'd like**
Like pandas solution df.loc[(df['Salary_in_1000']>=100) & (df['Age']< 60) & (df['FT_Team'].str.startswith('S')),['Name','FT_Team']]

is there alternative method for filter with Multiple conditions?  Thanks in advance.

**Comment by risenW** [comment]
@jasonwu513 This is not supported yet, but I will add it in the new version. You can track progress here https://github.com/opensource9ja/danfojs/pull/235

**Comment by risenW** [comment]
Added in latest version v0.3.0
