### ISSUE TITLE
Feature Request: Read Excel file into DataFrame Object

### ISSUE THREAD

**Issue by risenW** [opensource9ja/danfojs#27]
Excel is a popular format for storing data, so we intend to support it, we need to be able to read .xls files in danfo data structures. This should be in the [reader.py](https://github.com/opensource9ja/danfojs/blob/master/danfojs/src/io/reader.js) module and can look something like:

```javascript
// /**
//  * Reads a Excel file from local or remote address
//  * 
//  * @param {source} URL or local file path to retreive JSON file.
//  * @returns {Promise} DataFrame structure of parsed CSV data
//  */
// export const read_excel = async (source) => {
              data = read_parse_file(source)
              return new DataFrame(data)

// }

```

**Comment by adzo261** [comment]
Hi, can I work on this one?

**Comment by risenW** [comment]
> Hi, can I work on this one?

Sure you can, please go ahead. I'll assign you right away.
