### ISSUE TITLE
get_dummies function is not working properly 

### ISSUE THREAD

**Issue by PBird** [opensource9ja/danfojs#274]
**Describe the bug**
get_dummies works wrong when you give column parameter that is not first column name. For example, if you give columns parameter fruits it is going work fine but if you give Color or other ones this time it is going fail. 

**To Reproduce**
```
let data = { 
            fruits: ['pear', 'mango', "pawpaw", "mango", "bean"],
	    Color: ["Red", "Red", "Green", "Green", "Yellow"],
            Count: [20, 30, 89, 12, 30],
            Country: ["NG", "NG", "GH", "RU", "RU"] 
            }

let df = new dfd.DataFrame(data)
df.print()

let dum_df = dfd.get_dummies({ data: df, columns: ['Color']})
dum_df.print()
```

**Expected behavior**
get_dummies encode given columns properly

**Screenshots**
![image](https://user-images.githubusercontent.com/9611415/132423789-6c364b08-1658-46a4-9aba-cbe62e0566b3.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome 
 - Version: 0.2.8

**Comment by steveoni** [comment]
@PBird i will look into this. thanks

**Comment by steveoni** [comment]
@PBird 
Here is the fix for this issue; 
https://github.com/opensource9ja/danfojs/blob/7f369320e52bf2eff8556c30dfd9848884893799/danfojs-node/src/core/get_dummies.js#L80

the wrong column was accessed

this meant to be

```js
let col_idx = in_data.columns.indexOf(x); 
```

a pr will be created to change this
