### ISSUE TITLE
data_range not working

### ISSUE THREAD

**Issue by Riki96** [opensource9ja/danfojs#275]
**Describe the bug**
I tried using the function data_range as written in the examples on the main page, but it outputs the following error:
Uncaught Error: Kernel 'LinSpace' not registered for backend 'undefined'

**To Reproduce**
let data = new dfd.date_range({start:'2021-01-01', freq:'M', period:3});
console.log(data);

**Expected behavior**
Create a variable ranging from Start to End

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  92.0.4515.159

**Additional context**
I am using the CDN  <script src="https://cdn.jsdelivr.net/npm/danfojs@0.2.4/lib/bundle.min.js"></script>

**Comment by steveoni** [comment]
@Riki96 this is working as expected. please use the latest version

<img width="772" alt="Screen Shot 2021-09-09 at 00 12 33" src="https://user-images.githubusercontent.com/20904032/132601885-13f742a4-54db-4ca9-b02e-f9fd64d4372a.png">
