### ISSUE TITLE
Source data has "data" as a column header

### ISSUE THREAD

**Issue by maycheongs** [opensource9ja/danfojs#278]
Dataframe methods don't work if the datasource has dfd methods as a header eg "data" -- because the methods are using the column getter now instead of the dataframe data to do its operations.

As a result I cannot use this library  because the user MAYBE has a dataset with "data" as a column name.
The dataframe eventually needs to be converted back to a csv with its original column names which also won't work if "data" is a column name.

**To Reproduce**
My use case was a dfd.read_csv from a csv that had "data" as a column header.
const df = dfd.read_csv(csv_path)
const s_df = df.sample(10) <-- errors

**Expected behavior**
works as normal without having to rename columns first, or having to rename the column back to "data" AFTER converting the dataframe back to a csv.

Suggestion: Rename the dataframe data prop to be something more unique to this library e.g. __data or a unique word like danfo.

Edit: I thought about it some more from a developer-user perspective, and I think having column headers as a getter  (Dataframe.column_header to get the column data) was a great idea but it suddenly means the data source has a lot of key words that column headers cannot have i.e. all the df methods.

**Comment by risenW** [comment]
@maycheongs Fixed in the latest version v0.3.0
