### ISSUE TITLE
Replace index with mapped values

### ISSUE THREAD

**Issue by pguso** [opensource9ja/danfojs#283]
**Describe the bug**
Replace index with mapped values

**To Reproduce**
```typescript
const init = async () => {
    const df = await dfd.read_csv('../input/Pokemon.csv', {csvConfigs:{delimiter: ','}})
    
    df.set_index({key: "Name", inplace: true})
    
    df.index = df.index.map(i => i.replace(/.*(?=Mega)/, ""))
    df.head(10).print()
}
init();
```

**Expected behavior**
Pokemon Card names indexes replaced with sub string index.

**Additional context**
I try to make this tutorial https://www.kaggle.com/ash316/learn-pandas-with-pokemons with danfo

**Comment by pguso** [comment]
Also it seems that I don't get the right shape after changing the DataFrame

```typescript
const init = async () => {
    let df = await dfd.read_csv('../input/Pokemon.csv', {csvConfigs:{delimiter: ','}})
    
    df.set_index({key: "Name", inplace: true})

    df.drop({ columns: ["#"], axis: 1, inplace: true });

    console.log('The shape of the dataframe is: ', df.shape)    // shape of the dataframe
}
init();
```

The console.log shows the initial 13 columns but, I set one column as index and dropped another one, so it should be 11.

**Comment by pguso** [comment]
iloc doesn't seem to work after changing the index to none numeric values.

```typescript
const init = async () => {
    let df = await dfd.read_csv('../input/Pokemon.csv', {csvConfigs:{delimiter: ','}})
    
    df.set_index({key: "Name", inplace: true})
    
    let sub_df = df.iloc({rows: [0]})
    sub_df.print() //retrieves complete row date from index 0 ; integer version of loc
}
init();
```

Shows error:
_UnhandledPromiseRejection: Error: column index 12 is bigger than 11_

**Comment by risenW** [comment]
> Also it seems that I don't get the right shape after changing the DataFrame
> 
> ```ts
> const init = async () => {
>     let df = await dfd.read_csv('../input/Pokemon.csv', {csvConfigs:{delimiter: ','}})
>     
>     df.set_index({key: "Name", inplace: true})
> 
>     df.drop({ columns: ["#"], axis: 1, inplace: true });
> 
>     console.log('The shape of the dataframe is: ', df.shape)    // shape of the dataframe
> }
> init();
> ```
> 
> The console.log shows the initial 13 columns, but I set one column as index and dropped another one, it should be 11.

Change `key` parameter to `column` in set_index:
`df.set_index({column: "Name", inplace: true})`
