### ISSUE TITLE
Create Dataframe from json data which contains null value failure

### ISSUE THREAD

**Issue by BetterYan** [opensource9ja/danfojs#29]
I tried to create datafram from json data, but I got error. This is because there is null value. Can you handle this?

Below is the exception stack from browser:
index.min.js:10277 Uncaught TypeError: Cannot read property 'toString' of null
    at index.min.js:10277
    at Array.forEach (<anonymous>)
    at index.min.js:10277
    at Array.forEach (<anonymous>)
    at a.__get_t (index.min.js:10277)
    at DataFrame.__set_col_types (index.min.js:10560)
    at DataFrame.__read_object (index.min.js:10560)
    at new u (index.min.js:10560)
    at new DataFrame (index.min.js:10277)
    at <anonymous>:1:1

**Comment by BetterYan** [comment]
It works if I replace the null with undefined.

**Comment by risenW** [comment]
> It works if I replace the null with undefined.

Thanks for raising this issue. The function which automatically checks and convert undefined to NaN before DataFrame creation is [this](https://github.com/opensource9ja/danfojs/blob/3abf4ebfca7f767767916cbb57e57d4cd3d3ffc9/danfojs/src/core/utils.js#L199). For it to pick up null, we'd have to extend the test case. 

I'll take a look at this tomorrow, or would you like to work on it?

**Comment by risenW** [comment]
Fixed!
