### ISSUE TITLE
Applying JavaScript function to DataFrame not working

### ISSUE THREAD

**Issue by NikelausM** [opensource9ja/danfojs#292]
**Describe the bug**
TypeError thrown when using example code of the [apply functionality found in the documentation](https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.apply#apply-a-javascript-function-to-all-elements-in-dataframe).

**To Reproduce**
1. Create test.js
2. Copy and paste the following code:
```
const dfd = require("danfojs-node")

let data = [[1, 2, 3], [4, 5, 6], [20, 30, 40], [39, 89, 78]]
let cols = ["A", "B", "C"]
let df = new dfd.DataFrame(data, { columns: cols })

function sum_vals(x) {
    return x + 20
}

let df_new = df.apply({callable: sum_vals })
df_new.print()
```
3. Run: 
```node test.js```
4. See following error:
```
Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
<build_parent_directory>/build/node_modules/danfojs-node/dist/core/frame.js:1778
      return callable(row);
             ^

TypeError: callable is not a function
    at <build_parent_directory>/build/node_modules/danfojs-node/dist/core/frame.js:1778:14
    at Array.map (<anonymous>)
    at DataFrame.apply (<build_parent_directory>/build/node_modules/danfojs-node/dist/core/frame.js:1777:34)
    at Object.<anonymous> (<build_parent_directory>/build/scripts/test.js:11:17)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Expected behavior**
The altered dataframe should be printed as per that documentation example as shown below:
![image](https://user-images.githubusercontent.com/51514472/135730185-853d556c-5555-4e28-9aa8-789c26aa60ef.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version macOS BigSur 11.5.1

**Comment by risenW** [comment]
Hi, doc is a bit outdated for the apply method. I’ll ensure to update it. In the meantime, here’s a recent example of using apply:
