### ISSUE TITLE
Add plotting module back to Nodejs version

### ISSUE THREAD

**Issue by risenW** [opensource9ja/danfojs#297]
In order to support interactive plotting in the Nodejs Jupyter notebook, we need to add the plotting module and its types back to the danfojs-node lib. See discussion [here](https://github.com/DonJayamanne/typescript-notebook/issues/41).

**Comment by DonJayamanne** [comment]
@risenW DId you want me to submit a PR for this?

**Comment by risenW** [comment]
> @risenW DId you want me to submit a PR for this?

@DonJayamanne if you have the time, please do.

**Comment by DonJayamanne** [comment]
Thanks, sorry I didn't get to this, been very busy with an upcoming relocation...

**Comment by risenW** [comment]
> Thanks, sorry I didn't get to this, been very busy with an upcoming relocation...

@DonJayamanne No worries, I fixed this already, and pushed to the latest version v0.3.4
