### ISSUE TITLE
Inconsistent Data while creating Dataframe from array of array

### ISSUE THREAD

**Issue by akshay9** [opensource9ja/danfojs#299]
**Describe the bug**
Creating a new dataframe using 2D Tensor in danfojs-browser does not correctly map the object keys and column names

**To Reproduce**
Execute the following Code:
```js
const dfd = require("danfojs")

let testObj = [
  {
      "A": false,
      "B": false,
      "C": false,
  },
  {
      "B": false,
      "K": 443,
      "C": true,
  }
]

let df = new dfd.DataFrame(testObj)
df.print()
```
Output
╔════════════╤═══════════════════╤═══════════════════╤═══════════════════╗
║            │ A                 │ B                 │ C                 ║
╟────────────┼───────────────────┼───────────────────┼───────────────────╢
║ 0          │ false             │ false             │ false             ║
╟────────────┼───────────────────┼───────────────────┼───────────────────╢
║ 1          │ **false**             │ **443**               │ true              ║
╚════════════╧═══════════════════╧═══════════════════╧═══════════════════╝

**Expected behavior**
It should either throw an error that the column names are not consistent or should leave the column A blank for row index 1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version dafnojs 0.3.3

**Additional context**

**Comment by risenW** [comment]
Hi @akshay9 The format of your input data is not correct. If using an array of objects, then each entry corresponding to a row, and they must be in the same order.

This is the format we expect:

```javascript
let testObj = [
  {
      "A": false,
      "B": false,
      "C": false,
  },
  {
      "A": false,
      "B": 443,
      "C": true,
  }
]

```
