### ISSUE TITLE
the query example is not work

### ISSUE THREAD

**Issue by BetterYan** [opensource9ja/danfojs#30]
It throws error. 
The example code is from https://danfo.jsdata.org/getting-started#selection.
At section "Selecting values from a DataFrame works on string columns:"

let data = [{"A": ["Ng", "Yu", "Mo", "Ng"]},
            {"B": [34, 4, 5, 6]}, 
             {"C": [20, 20, 30, 40]}]
let df = new dfd.DataFrame(data)

df.print()

let query_df = df.query({ column: "A", is: "==", to: "Ng"})
query_df.print() //after query

index.min.js:10560 
 Shape: (3,1,4) 

index.min.js:10560 
╔═══╤═══════════════════╗
║   │ A                 ║
╟───┼───────────────────╢
║ 0 │ Ng,Yu,Mo,Ng       ║
╟───┼───────────────────╢
║ 1 │ 34,4,5,6          ║
╟───┼───────────────────╢
║ 2 │ 20,20,30,40       ║
╚═══╧═══════════════════╝

VM74817:1 Uncaught ReferenceError: Ng is not defined
    at eval (eval at query (index.min.js:10277), <anonymous>:1:1)
    at DataFrame.query (index.min.js:10277)
    at <anonymous>:8:19

**Comment by JhennerTigreros** [comment]
This problem is already solved in source code in PR #23. can you try to update the module?

**Comment by risenW** [comment]
> This problem is already solved in source code in PR #23. can you try to update the module?

I'm currently working on some last minute fix, will definitely push out a new version by Thursday.

**Comment by Teut2711** [comment]
I installed from npm yesterday only. Same issue. On querying column headers change to  numbers.


![image](https://user-images.githubusercontent.com/40588378/141367787-e231c948-2c21-4a5f-b5eb-2824c1a48c29.png)

**Comment by risenW** [comment]
@Teut2711 Can you update to the latest version of danfojs. I just tried and it's working fine. 

<img width="633" alt="Screen Shot 2021-11-12 at 8 59 10 AM" src="https://user-images.githubusercontent.com/29900845/141431415-6c122f39-34ca-4cfb-a9fc-0ab3f1a68031.png">

**Comment by Teut2711** [comment]
That's weird. I have  "dependencies": {
    "danfojs-node": "^0.3.3"
  },
