### ISSUE TITLE
Error: package.json does not exist - Danfojs-node does not work with webpack based bundlers.

### ISSUE THREAD

**Issue by jordantoaster** [opensource9ja/danfojs#301]
**Describe the bug**
I am currently using DanfoJS in a Node JS project, my aim is to deploy the solution to an AWS Lambda. Danfo JS introduces a handful of issues that stops this from being possible:

- The DanfoJS Library cannot be minified with any Webpack compatible optimisers (in my case I am using the serverless plugin "serverless-plugin-optimize").

Questions: 

- Is there a way to enable the danfojs-node npm package to support typical webpack deployment processes? tfjs-node appears to not be webpack compatible, therefore making danfojs-node incompatible with webpack.
- Is this an expected limitation?

**To Reproduce**
1. Install danfojs-node as you would normally in a serverless project.
2. Install the plugin for serverless "serverless-plugin-optimize"
3. Run `sls invoke local -f function-name`
4. You will then be faced with an error:

> Error: package.json does not exist at /Users/jordan.mcdonald/Applications/ml-product-candidate-auto-match/_optimize/ml-product-candidate-auto-match-dev/src/node_modules/@tensorflow/tfjs-node/package.json
    at Object.exports.find (/Users/jordan.mcdonald/Applications/ml-product-candidate-auto-match/_optimize/ml-product-candidate-auto-match-dev/src/main.js:119468:15)
    at Object.<anonymous> (/Users/jordan.mcdonald/Applications/ml-product-candidate-auto-match/_optimize/ml-product-candidate-auto-match-dev/src/main.js:101995:26)

**Desktop (please complete the following information):**
 - Mac
 - Node 14.13
 - Latest version of danfojs-node

**Comment by risenW** [comment]
@jordantoaster You cannot build Danfojs-node with webpaxk, because most of the libs used in Danfojs-node version only works in Nodejs environment. 

You should consider using the Danfojs browser based version of you need to bundle with webpaxk. See : https://www.npmjs.com/package/danfojs

**Comment by jordantoaster** [comment]
Thanks @risenW, I should have clarified I do not mean web packs in the traditional usage of the term. I am referring to web packs particularly for node for deploying to node run times, example of one below:

https://www.npmjs.com/package/serverless-webpack

**Comment by joshpopelka20** [comment]
@jordantoaster - were you ever able to figure this out? I'm trying to do something similar using danfojs with Nodejs runtime in AWS Lambda
