### ISSUE TITLE
DataFrame.query() resets the column names.

### ISSUE THREAD

**Issue by sanchaz** [opensource9ja/danfojs#302]
**Describe the bug**
DataFrame.query() by string resets the columns to 0, 1, 2, ...
https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.query#query-by-a-string-column-in-a-dataframe
According to the docs the columns should remain there.

**To Reproduce**
https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.query#query-by-a-string-column-in-a-dataframe
Copy the example posted and run it.

However if you use inplace: true then the behaviour is correct.
Seems the issue is that when returning a new df it forgets to copy the columns.

**Expected behavior**
Column names should remain the same.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 93.0 (64-bit)

**Additional context**

**Comment by risenW** [comment]
FIXED!
