### ISSUE TITLE
read_excel does not parse date columns correctly

### ISSUE THREAD

**Issue by rjkey** [opensource9ja/danfojs#307]
**Describe the bug**
I have a column in my excel-file which contains dates in this format (D/M/YYYY)/(DD/MM/YYYY)
When I use the `read_excel` function in danfojs-node, it spits out a number instead of the date as a string or similar. 

Example: The date "1/1/2020" got converted to 43898. 

**To Reproduce**
1. Have a excel document with a date column
2. Read the excel file with the `read_excel` function in danfojs-node
3. The format of the date in your Dataframe is not a date anymore but a number

**Expected behavior**
The Dataframe should have date strings and not numbers

**Desktop (please complete the following information):**
 - Windows 10
- Node 16.7
- Danfojs-node 0.3.3

**Comment by risenW** [comment]
> **Describe the bug** I have a column in my excel-file which contains dates in this format (D/M/YYYY)/(DD/MM/YYYY) When I use the `read_excel` function in danfojs-node, it spits out a number instead of the date as a string or similar.
> 
> Example: The date "1/1/2020" got converted to 43898.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Have a excel document with a date column
> 2. Read the excel file with the `read_excel` function in danfojs-node
> 3. The format of the date in your Dataframe is not a date anymore but a number
> 
> **Expected behavior** The Dataframe should have date strings and not numbers
> 
> **Desktop (please complete the following information):**
> 
> * Windows 10
> * Node 16.7
> * Danfojs-node 0.3.3

Interesting, we currently use the [xlxs](https://www.npmjs.com/package/xlsx) library for loading excel files, this could be an issue with the lib.

**Comment by risenW** [comment]
This is a minor issue with xlxs library, so closing
