### ISSUE TITLE
Operations between columns

### ISSUE THREAD

**Issue by iserranoe** [opensource9ja/danfojs#309]
Sorry if this feature is already implemented, but I can't figure out how to do it. It is possilbe to perform operations between columns or obtain derived columns as in Pandas?

```
df['new_column'] = df['old_column] *2
df['sum_column'] = df['A']+df['B']
```

What I did so far for the first operation is using `.map` and `.addColum`

```
const m = df['old_column'].map((x)=>2*x).values
df.addColumn({"column":"new_column", "values": m, inplace: true})
```
How could I do the sum between columns?

**Comment by risenW** [comment]
You can call the math functions directly on a column. For example to add column A and B, you can do the following:

df[“A”].add(df[“B”])

See: https://danfo.jsdata.org/api-reference/series#binary-operator-functions
