### ISSUE TITLE
DataFrame groupby typings does not follow groupby implementation

### ISSUE THREAD

**Issue by Devwulf** [opensource9ja/danfojs#315]
Hello! I've noticed that the `groupby()` typings for dataframes do not follow the intended implementation of the `groupby()` function. 

The documentation here: 
https://github.com/opensource9ja/danfojs/blob/146ba82ca723527f5c2008b5077c6a13d196e01f/danfojs-browser/src/core/frame.js#L2310
states that the `col` parameter is a list of (string) columns, while the typing here:
https://github.com/opensource9ja/danfojs/blob/146ba82ca723527f5c2008b5077c6a13d196e01f/danfojs-browser/types/core/frame.d.ts#L554
declares that the function only takes in a string value. This will probably lead to errors when used, since string values are not mappable. 

Also, perhaps this parameter can be made optional by allowing it to be undefined?

**Comment by risenW** [comment]
Thanks for raising this. @steveoni Can you update this

**Comment by risenW** [comment]
Fixed!
