### ISSUE TITLE
Editing required to run latest version on Windows 10

### ISSUE THREAD

**Issue by burque505** [opensource9ja/danfojs#32]
In @tensorflow/tfjs-node/dist/index.js, line 58:
`
var bindings = bindingPath;  // var bindings = require(bindingPath);
`
In @tensorflow/tfjs-node/dist/nodejs_kernel_backend.js, line 77:
`
        _this.isUsingGpuDevice = false; //        _this.isUsingGpuDevice = _this.binding.isUsingGpuDevice(); - function doesn't exist
`

**Comment by risenW** [comment]
Duplicate: #33
