### ISSUE TITLE
Cell Styles Override Header Styles in Plotly Tables

### ISSUE THREAD

**Issue by robertwalsh0** [opensource9ja/danfojs#34]
I've found that, when plotting tables, `header_style` will be overwritten by `cell_style`

As you can see in the image below, the headers should be `#333` but instead are overridden by the cell styles `red`.

Link to codepen: https://codepen.io/robwalsh0/pen/GRqRXOK

<img width="1420" alt="Screen Shot 2020-10-07 at 7 55 05 PM" src="https://user-images.githubusercontent.com/88433/95403159-13510600-08d7-11eb-97a0-7d528116a027.png">

**Comment by risenW** [comment]
Thanks for raising this issue. I was able to reproduce it. I'll work on this ASAP

**Comment by robertwalsh0** [comment]
@risenW Thank you! I've also been unable to change the widths of columns by following the instructions listed in your docs. Could you also verify that this is possible, and if so, document how that works?

**Comment by risenW** [comment]
@robertwalsh0 Thanks for this fix! I'm merging now.
