### ISSUE TITLE
Cannot call  Series.min() or mean()

### ISSUE THREAD

**Issue by code-wizard** [opensource9ja/danfojs#35]
For some reason I cannot call ```min(), mean()``` on a Series but I can call ```max() and mode()```. See code below ( from the get started example) [https://danfo.jsdata.org/api-reference/series/series.min](url)

Danfo.js version: [https://cdn.jsdelivr.net/npm/danfojs@0.1.2/dist/index.min.js](url)

```
data2 = [1,2,3,4,5,6,8]
sf2 = new dfd.Series(data2)
console.log(sf2.values)
```

I am using Danfo Notebook and this is the error message

```
TypeError: o.incRef is not a function
```

**Comment by steveoni** [comment]
using the Dnotebook ibwas not able to reproduce the error.

Did you load this version of danfojs using `load_package` in the notebook

**Comment by code-wizard** [comment]
Yes I loaded the package

```
load_package(["https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest","https://cdnjs.cloudflare.com/ajax/libs/mathjs/7.5.0/math.min.js",
              "https://cdn.jsdelivr.net/npm/danfojs@0.1.2/dist/index.min.js"])
```

**Comment by steveoni** [comment]
ok. now I'm getting same error.

the issue is from the tensorflow latest. Danfo.js is using the tensor  operation from tensorflow. 

Try removing the tensorflow/tjs@latest. This fix the error

**Comment by code-wizard** [comment]
Closing this issue as this fixed the error. 

Lastly, is there any plan to integrate with math.js just as pandas integrates with NumPy?
