### ISSUE TITLE
Wrong exception thrown for empty dataframe

### ISSUE THREAD

**Issue by code-wizard** [opensource9ja/danfojs#37]
Using the get started query example
[https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.query](url)

```
let data = {"A": [30, 1, 2, 3],
           "B": [34, 4, 5, 6],
           "C": [20, 20, 30, 40]}
           
let cols = ["A", "B", "C"]
let df = new dfd.DataFrame(data, { columns: cols })
df.print() //before query

let query_df = df.query({ "column": "B", "is": ">", "to": 5 })
table(query_df)
```

I modified the condition to 
```
let data = {"A": [30, 1, 2, 3],
           "B": [34, 4, 5, 6],
           "C": [20, 20, 30, 40]}
           
let cols = ["A", "B", "C"]
let df = new dfd.DataFrame(data, { columns: cols })
df.print() //before query

let query_df = df.query({ "column": "B", "is": ">", "to": 40 })
table(query_df)
```
Error message
```
File format not supported for now
```
Expected Output: Return empty result/array

**Comment by steveoni** [comment]
oh. that should give am error.

since the column B does not have the value 40, hence its passing empty array to the dataframe.

the error is ment to catch though.

Thanks

**Comment by risenW** [comment]
@steveoni would you work on this?

**Comment by risenW** [comment]
@steveoni any update on this?

**Comment by steveoni** [comment]
Now fixed

**Comment by mgiedrikas** [comment]
this is the same is for strings, ie. if B has string instead of numbers and if you do this:
`let query_df = df.query({ "column": "B", "is": "==", "to": "foo" })`

I am getting the same error - `File format not supported for now`

**Comment by iGorjidooz** [comment]
Hi everyone! When I am querying a DataFrame which would return an empty result, danfojs-node throws the following error (as it is implemented in core/frame.js)
`Error: query returned empty data`
but shouldn't it actually return an empty DataFrame like in Pandas?
IMO, throwing an error breaks the chain of execution and it would make it difficult in cases where a decision is dependent on the query to return empty result or not.

**Comment by vxm5091** [comment]
> Hi everyone! When I am querying a DataFrame which would return an empty result, danfojs-node throws the following error (as it is implemented in core/frame.js)
> `Error: query returned empty data`
> but shouldn't it actually return an empty DataFrame like in Pandas?
> IMO, throwing an error breaks the chain of execution and it would make it difficult in cases where a decision is dependent on the query to return empty result or not.

Did you find a workaround to this? I'm having a similar issue.

**Comment by risenW** [comment]
I'm working on a fix

**Comment by Equidem** [comment]
@risenW any progress on the fix?

**Comment by risenW** [comment]
D

**Comment by risenW** [comment]
This has been fixed in the latest conversion to TS. See #235
