### ISSUE TITLE
Feature request: New Query operator !=

### ISSUE THREAD

**Issue by manuelitox** [opensource9ja/danfojs#39]
Hey folks! 

Firstly, I want to say this project is awesome. I've been playing with him for two weeks and I've had a lot of fun

I have a little suggestion, when I'm trying to get a new data frame excluding a column value I'd like to use the query method by a new parameter (operator). Example:

```javascript
const data = {
  'countries': ['Venezuela', 'Argentina', 'Colombia', 'Spain']
  'capital': ['Caracas', 'Buenos Aires', 'Bogota', 'Madrid']
}

let df = new dfd.DataFrame(data)
df = df.query({ "column": "countries", "is": "!=", "to": 'Spain' })

df.print()

// returns a countries table without the Spain row. 
```

It could be a powerful addition. I'd love to collab with a PR, please let me know your thoughts.

**Comment by risenW** [comment]
@manuelitox Thanks for spotting that, you can go ahead and add it. I'll merge it

**Comment by risenW** [comment]
Added! Thanks

**Comment by manuelitox** [comment]
Awesome! I was going to work in that today haha.

Btw, could be useful to add the new operator in the DataFrame.query [docucmentation](https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.query#query-by-a-string-column-in-a-dataframe).
