### ISSUE TITLE
Support flexible plotting

### ISSUE THREAD

**Issue by domoritz** [opensource9ja/danfojs#4]
It would be great if danfo was agnostic to a particular plotting library and supported for example [Vega-Lite](https://vega.github.io/vega-lite/) and in particular https://github.com/vega/vega-lite-api.

**Comment by risenW** [comment]
Hi @domoritz thanks for the feedback. We would definitely love to support numerous plotting library, but we had to bundle danfo with one. I believe we can can create wrappers that works with different backends going forward.

**Comment by domoritz** [comment]
Sounds great. Just wondering, why do you think danfo needs to be bundled with a plotting library. Wouldn't it be better to keep the dependencies lean and provide plotting as an extension? Instead of making `.plot` a function of a dataframe, you could even turn it around and `plat(df)`. I can see that you want to stay close to Pandas but in js dependencies are a lot more expensive than in Python since you usually have to load the complete dependencies every time you run the code.

**Comment by risenW** [comment]
I totally get your point, what I think we can do is remove the plotting dependency and have users require it instead. Or we can create a more generic plotting module that can work with numerous plotting packages as you have earlier mentioned. 
We can definitely redesign this if you're interested in working with us on it.

**Comment by willium** [comment]
+1 on not bundling a plotting library. Doesn't seem germane to the problems that this attempts to solve (dataframes).

**Comment by domoritz** [comment]
I think unbundling plotting is probably the best approach as there are many js plotting libraries and it's not clear which one makes the most sense in a particular use case.

**Comment by Alex-Monahan** [comment]
Plotly is actually perfect for me, and I love having a .plot method on your DataFrame object! Please don't remove that capability, or please show me a path to re-import it! :-)

**Comment by domoritz** [comment]
The plotting library could extend danafo or you could call `plot(dataFrame, ...)` where you call `dataFrame.plot(...)` today.

**Comment by steveoni** [comment]
> The plotting library could extend danafo or you could call `plot(dataFrame, ...)` where you call `dataFrame.plot(...)` today.

I totally agree with that. We can try creating a wrapper for some of the popular plotting libaries

**Comment by risenW** [comment]
> Plotly is actually perfect for me, and I love having a .plot method on your DataFrame object! Please don't remove that capability, or please show me a path to re-import it! :-)

Sure we won't remove support for it, we will just not bundle it together to reduce size, and then create a wrapped for it. This ensures we can create separate wrappers for different plotting package. 

So we can do something similar to Plot(dataframe, Plotly) or Plot(dataframe, Vega)
