### ISSUE TITLE
Feature Request: provide ESM conform dist target

### ISSUE THREAD

**Issue by merryman** [opensource9ja/danfojs#40]
I noticed this while I was trying to import danfojs via the https://jspm.dev cdn.
Right now the distributed script of danfos expects itself to be executed globally.
That is all fine and dandy as long as you either include the script tag directly into the dom or load the script manually in the browser. However it kind of causes problems when you want to use danfojs in the context of an ES-Module based build system.
Since every declared variable inside a ES-Module is local to that module, the dfd var is not exposed and can also not be accessed via the global window (since danfojs is run in its own context).
Is it possible to add an additional target in the webpack bundle that provides an esm conform export of the dfd variable?
I think that should do the job.

Thank you for the hard work!

**Comment by risenW** [comment]
Thanks for pointing this out. I'll look into it. Meanwhile if you have any pointers, or fix for it please don't hesitate to add it. 
Webpack config can be a pain most times 😄

**Comment by merryman** [comment]
I added a quick fix in #42

**Comment by risenW** [comment]
Thanks, merged!
