### ISSUE TITLE
Dataframe pivot functionality

### ISSUE THREAD

**Issue by vinchauhan** [opensource9ja/danfojs#47]
Do we have the dataframe pivoting functionality in danfo?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html?highlight=pivot#pandas.DataFrame.pivot

**Comment by risenW** [comment]
This issue has been raised in #9. No one is working on it at the moment. If you would like to do this, let me know so I can assign you to it.

**Comment by MCYouks** [comment]
Hello 👋 Any update on this issue ?

**Comment by SathishRaju** [comment]
Hey, any updates on this one?

**Comment by steveoni** [comment]
@SathishRaju at the moment no update, but it's added to the list of features
