### ISSUE TITLE
Use in the client side using react

### ISSUE THREAD

**Issue by camilotorresideas** [opensource9ja/danfojs#53]
Hi,

It is possible to use Danfo.js in the client side through react js?

Thanks

**Comment by risenW** [comment]
> Hi,
> 
> It is possible to use Danfo.js in the client side through react js?
> 
> Thanks

Yes, it's definitely possible. Just as you would import and use any other Javascript package

**Comment by camilotorresideas** [comment]
Ok, thank you for the answer. Which package should I install, because with danfojs-node it does not run, an error shows up (I assume it needs node to run). With "npm install danfojs" the react app does run but when I create a dataframe with a json array it throws an error saying the param is undefined (and is not). Maybe I'm using the wrong package or I need to install other packages. Again, thanks for your work 👍

**Comment by camilotorresideas** [comment]
I was importing wrong the package. In react I use this "import { DataFrame } from "danfojs/danfojs/src/core/frame" and it works. If there is another way to do the import and work with the dataframe object let me know. Thanks for your help!
