### ISSUE TITLE
Creating empty DataFrames as in pandas

### ISSUE THREAD

**Issue by srinivas-tlt** [opensource9ja/danfojs#55]
newDF = pd.DataFrame() 

In danfojs DataFrame class expects two parameters with first parameter being data in object[ ] or array[] type. Tried passing both but, I am getting error .
```
1. core.js:4442 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Utils.__get_t (utils.js:245)

2..Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
```

Using  danfojs v 0.1.2 (cilent)

**Comment by risenW** [comment]
@srinivas-tlt Thanks for opening this issue. This is very important, and will surely be implemented.

**Comment by risenW** [comment]
@opeyemibami Can you work on this issue?
