### ISSUE TITLE
Does danfojs support observable/reactive concepts / change events?

### ISSUE THREAD

**Issue by stefaneidelloth** [opensource9ja/danfojs#56]
I would like to react on cell changes, so that I am able to only update those parts of my
table calculations that I need to update.

=>Does danfojs provide some concept of observable cells, reactive calculations, change events?

(How does it relate to RxJs and RxDb https://github.com/pubkey/rxdb ?)

**Comment by risenW** [comment]
Hi @stefaneidelloth not at the moment. Could be considered in the future if we see more request/need for it.
