### ISSUE TITLE
Danfo.js benchmarks?

### ISSUE THREAD

**Issue by Alex-Monahan** [opensource9ja/danfojs#59]
Hello!

I have a few quick questions!

Are there any performance benchmarks of danfo.js? I am trying to decide if Danfo would be faster than vanilla JS operations for groupings, getting distinct values by column, and joins. How does memory consumption compare?

Also, which TF.js backend is used when running in the browser (Chrome)? Does danfo.js block the main DOM thread when used in the browser?

Thanks!
-Alex

**Comment by risenW** [comment]
Some answers to your questions. 

1. There are no performance official benchmarks for now. Most operations (especially mathematical ops) should be faster because we're using tfjs under the hood. 
2. In the browser, we are using @tensorflow/tfjs, it's optimised with webgl and makes math ops faster as well.
3. Most functions are asynchronous, and should not block the main thread.

**Comment by risenW** [comment]
@opeyemibami can you do some benchmarks comparison between danfojs ops and vanilla Js?

**Comment by motin** [comment]
On this topic, it would be very interesting to see how/if mentioned Danfo operations benefit from the tfjs wasm backend (https://www.npmjs.com/package/@tensorflow/tfjs-backend-wasm). If you benchmark, please include that in the benchmarks! :)

**Comment by batjko** [comment]
A related topic would be memory requirements.
I'm only minimally familiar with pandas and don't know how they do it, but how are large datasets affecting memory usage? If I have a 10MB json and apply a few transforms on it that return new data frames each time, is any stream processing used that Node is very famous for, for example?

**Comment by nite** [comment]
I'm just doing a spike with danfo, and came across this post. 

I might be missing something, but I have this spike: 
https://codesandbox.io/s/danfojs-sandbox-ivyzk

A simple groupBy with lodash takes 53ms, and with danfo 42s. 
What am I missing? 

```
t1 53.80000001192093
t2 42480.09999996424 
```
