### ISSUE TITLE
StandartScaler results

### ISSUE THREAD

**Issue by ijakparov** [opensource9ja/danfojs#60]
Why Danfojs StandartScaler results don’t  equal to python sklear.StandartScaler results?

**Comment by steveoni** [comment]
it should. can you share your code and result?

**Comment by ijakparov** [comment]
> it should. can you share your code and result?

pyton
`from sklearn.preprocessing import StandardScaler
import pandas as pd

somedata = [[100,1000,2000, 3000] ,
            [20, 30, 89, 12],
            [1, 1, 1, 0]];
df = pd.DataFrame(data=somedata)

scaler = StandardScaler()
result = scaler.fit_transform(df)
`

Result is array([[ 1.39090235,  1.41375362,  1.41314026,  1.41420504],
       [-0.47399466, -0.67564356, -0.65886309, -0.7028514 ],
       [-0.91690769, -0.73811007, -0.75427717, -0.71135364]])

js
`const tf = require("@tensorflow/tfjs-node")
const dfd = require("danfojs-node")

let scaler = new dfd.StandardScaler()

let data = [
    [100,1000,2000, 3000] ,
    [20, 30, 89, 12],
    [1, 1, 1, 0]
]
              
let df = new dfd.DataFrame(data)

scaler.fit(df)

let sf_enc = scaler.transform(df)
sf_enc.print()`

Result is ═══╤═══════════════════╤═══════════════════╤═══════════════════╤═══════════════════╗
║   │ 0                 │ 1                 │ 2                 │ 3                 ║
╟───┼───────────────────┼───────────────────┼───────────────────┼───────────────────╢
║ 0 │ -0.4258379936...  │ 0.48414421081...  │ 1.49523544311...  │ 2.50632691383...  ║
╟───┼───────────────────┼───────────────────┼───────────────────┼───────────────────╢
║ 1 │ -0.5067253112...  │ -0.4966143667...  │ -0.4369599819...  │ -0.5148140192...  ║
╟───┼───────────────────┼───────────────────┼───────────────────┼───────────────────╢
║ 2 │ -0.5259360074...  │ -0.5259360074...  │ -0.5259360074...  │ -0.5269471406...  ║

**Comment by steveoni** [comment]
I will check it out

**Comment by risenW** [comment]
@steveoni any updates on this?

**Comment by steveoni** [comment]
@ijakparov the standscalar bug is now fixed.
