### ISSUE TITLE
TensorFlow.js Double includes

### ISSUE THREAD

**Issue by GantMan** [opensource9ja/danfojs#63]
Should TensorFlow.js be a peer dependency?  I'm having some issues trying to include Danfo.js and when I'm in Node, I get errors when I try to bring `tf`.

I have similar issues when I try to bring it in on observablehq

<img width="1374" alt="Screen Shot 2020-12-06 at 8 19 00 PM" src="https://user-images.githubusercontent.com/997157/101302075-498c0280-3800-11eb-89a6-585eb6fbfea2.png">

My guess is that you might need the TF version to be a peer dependency.  If that's a no-go, then you'll need to expose your included version of TFJS with something like `cosnt tf = dfd.tfjs`

**Comment by risenW** [comment]
Yes, thanks for noticing this, we do need to add TFJS as a peer dependency.

**Comment by GantMan** [comment]
let me know if you'd like me to do this PR.  I'd be happy to help.

**Comment by risenW** [comment]
Fixed in #71
