### ISSUE TITLE
Peer dependency for danfojs-node

### ISSUE THREAD

**Issue by GantMan** [opensource9ja/danfojs#66]
Seems the node version still has a strict dependency not a peer dependency

https://github.com/opensource9ja/danfojs/blob/849d14c8e7fa79bce4ffa9d0d177639047313520/package-config-web.txt#L108-L109

This causes an issue on my Mac.

**Comment by risenW** [comment]
This is also causing some issues in browser-side, we'll be using the @tensorflow/tfjs module for now
