### ISSUE TITLE
`to_csv` is not correct

### ISSUE THREAD

**Issue by GantMan** [opensource9ja/danfojs#67]
Documentation demonstrates that you need to provide the path to a CSV file, suggesting it will save the contents there.

It does not.

DOCS: https://danfo.jsdata.org/api-reference/dataframe/dataframe.to_csv
CODE: https://github.com/opensource9ja/danfojs/blob/master/danfojs/src/core/generic.js#L373

I assume it was supposed to save a file?  Are the docs correct and the implementation wrong?

**Comment by risenW** [comment]
Docs are correct, implementation is not complete for now. Would you like to work on this?

**Comment by GantMan** [comment]
Yup.  Question:  How do you identify and change behavior when in Node and when in Web?

Are you manually making builds or is there a conditional you're using?

**Comment by GantMan** [comment]
I did a PR that I believe fits the needs.   Please let me know.

**Comment by risenW** [comment]
> I did a PR that I believe fits the needs. Please let me know.

Checking it now

**Comment by GantMan** [comment]
let me know when you do a new release.  I'll do a smoketest.

**Comment by risenW** [comment]
> let me know when you do a new release. I'll do a smoketest.

I actually did that already. Two days back. Do check

**Comment by GantMan** [comment]
Works great!  However, what do you think about adjusting it, so no parameter means just return CSV string?
