### ISSUE TITLE
plotly.newplot() call missing parameter

### ISSUE THREAD

**Issue by secretlyamble** [opensource9ja/danfojs#69]
Heya!  It looks like many (if not all) of the calls to `plotly.newPlot()` are missing the `config` parameter (fourth param).  This prevents consumers from passing config options to plotly such as `displayLogo: false`.

The fix looks like it should be as simple as replacing all instances of `newPlot(this.div, [trace], this_config['layout']);` with `newPlot(this.div, [trace], this_config['layout'], this_config);` in `danfojs/src/plotting/plot.js`.  I have tried this on a local branch and it seems to work!

**Comment by secretlyamble** [comment]
created https://github.com/opensource9ja/danfojs/pull/70 to hopefully help fix (sorry if I didn't do this correctly, I'm new)

**Comment by risenW** [comment]
> created #70 to hopefully help fix (sorry if I didn't do this correctly, I'm new)

@secretlyamble  Thanks for this fix! Tested and merged already.
