### ISSUE TITLE
Data frame rename does not work as specify

### ISSUE THREAD

**Issue by opeyemibami** [opensource9ja/danfojs#7]
Setting inplace to "true" or "false" seems not to be working as expected 
`{
  df.rename({mapper:{'type':'wine_type'},inplace:true})
  return print(df.head())
}
`
`{
  df.rename({mapper:{'type':'wine_type'},inplace:false})
  return print(df.head())
}`

both code snippet output same result which is not supposed to be so.

**Comment by risenW** [comment]
Thanks for raising this issue, it has been fixed and will roll out in the next patch.
