### ISSUE TITLE
npm danfojs-node outdated

### ISSUE THREAD

**Issue by asjsrep** [opensource9ja/danfojs#72]
The node version pulled from npm appears to outdated. Is there a reason why it's behind? 

https://www.npmjs.com/package/danfojs-node/v/0.1.5

**Comment by risenW** [comment]
@asjsrep I've not pushed the latest changes to npm. I'm on it currently

**Comment by risenW** [comment]
Updated to v0.1.6. See [link](https://www.npmjs.com/package/danfojs-node)
