### ISSUE TITLE
DF.Sort Values

### ISSUE THREAD

**Issue by grpandi** [opensource9ja/danfojs#74]
Sorting values giving wrong result when we have duplicate value in the sorting column. 

Dataframe before sorting:
![image](https://user-images.githubusercontent.com/46180269/103082359-3176fa00-45da-11eb-9ac7-ad722b241f26.png)

╔═══╤═══════════════════╤═══════════════════╗
║   │ fam               │ fam_count         ║
╟───┼───────────────────┼───────────────────╢
║ 0 │ fFZX              │ 4                 ║
╟───┼───────────────────┼───────────────────╢
║ 1 │ fFVX              │ 12                ║
╟───┼───────────────────┼───────────────────╢
║ 2 │ fU5X              │ 16                ║
╟───┼───────────────────┼───────────────────╢
║ 3 │ fULX              │ 2                 ║
╟───┼───────────────────┼───────────────────╢
║ 4 │ fDHX              │ 3                 ║
╟───┼───────────────────┼───────────────────╢
║ 5 │ fWNX              │ 2                 ║
╟───┼───────────────────┼───────────────────╢
║ 6 │ f78X              │ 3                 ║
╚═══╧═══════════════════╧═══════════════════╝

Dataframe after Sort values:

╔═══╤═══════════════════╤═══════════════════╗
║   │ fam               │ fam_count         ║
╟───┼───────────────────┼───────────────────╢
║ 3 │ fULX              │ 2                 ║
╟───┼───────────────────┼───────────────────╢
║ 3 │ fULX              │ 2                 ║
╟───┼───────────────────┼───────────────────╢
║ 4 │ fDHX              │ 3                 ║
╟───┼───────────────────┼───────────────────╢
║ 4 │ fDHX              │ 3                 ║
╟───┼───────────────────┼───────────────────╢
║ 0 │ fFZX              │ 4                 ║
╟───┼───────────────────┼───────────────────╢
║ 1 │ fFVX              │ 12                ║
╟───┼───────────────────┼───────────────────╢
║ 2 │ fU5X              │ 16                ║
╚═══╧═══════════════════╧═══════════════════╝

index 5, 6 are missing and 3 and 4 are duplicating.

**Comment by MCYouks** [comment]
Up ! I also encounter a similar issue (see #75) when sorting a frame after applying a `groupby` method.

In my case, the negative values are sorted in a descending way, while positive values are sorted in an ascending way.

**Comment by steveoni** [comment]
@grpandi and @MCYouks this issue and #75  is now fixed.
