### ISSUE TITLE
DataFrame.sort_values not working properly

### ISSUE THREAD

**Issue by MCYouks** [opensource9ja/danfojs#75]
Hello everybody 👋

When applying `sort_values` method to a data frame column that contains both positive and negative `float32` type values, the values are not properly sorted.

In fact, the negative values are sorted in a descending order (↓), while positive values are sorted in an ascending order (↑).

As you can notice below, after applying the method `df.sort_values({ by: "amount_sum", inplace: true });` I get returned the following data frame 👇

╔════╤═══════════════════╤═══════════════════╗
║                │ counterpartyName                                       │ amount_sum        ║
╟────┼───────────────────┼───────────────────╢
║ 14           │ Apple                                                             │ -0.99             ║
╟────┼───────────────────┼───────────────────╢
║ 17           │ Super.so                                                        │ -3.35             ║
╟────┼───────────────────┼───────────────────╢
║ 3            │ Notion                                                            │ -4.86             ║
╟────┼───────────────────┼───────────────────╢
║ 5             │ Airtable                                                         │ -12.39            ║
╟────┼───────────────────┼───────────────────╢
║ 1             │ Umso                                                             │ -23.82            ║
╟────┼───────────────────┼───────────────────╢
║ 6            │ Bouygues Telecom                                       │ -23.98            ║
╟────┼───────────────────┼───────────────────╢
║ 16           │ Franprix                                                         │ -99.92            ║
╟────┼───────────────────┼───────────────────╢
║ 13           │ Free Mobile                                                   │ -112.07           ║
╟────┼───────────────────┼───────────────────╢
║ 8             │ Google Suite                                                 │ -130.72           ║
╟────┼───────────────────┼───────────────────╢
║ 4             │ Monoprix                                                       │ -141.88           ║
╟────┼───────────────────┼───────────────────╢
║ 18           │ RATP                                                              │ -159.72           ║
╟────┼───────────────────┼───────────────────╢
║ 15           │ La Banque Pos...                                           │ -209.94           ║
╟────┼───────────────────┼───────────────────╢
║ 10           │ Autres frais ...                                               │ -258.17999        ║
╟────┼───────────────────┼───────────────────╢
║ 7             │ Alan                                                               │ -275.89999        ║
╟────┼───────────────────┼───────────────────╢
║ 9             │ Amazon                                                         │ -282.95999        ║
╟────┼───────────────────┼───────────────────╢
║ 12           │ Oui SNCF                                                      │ 0                 ║
╟────┼───────────────────┼───────────────────╢
║ 11            │ 8                                                                    │ 87.55             ║
╟────┼───────────────────┼───────────────────╢
║ 0             │ undefined                                                      │ 2124.36011        ║
╟────┼───────────────────┼───────────────────╢
║ 2             │ CAF                                                                │ 2138.04004        ║
╚════╧═══════════════════╧═══════════════════╝

Does someone understand why the values are not properly sorted ?

Regards,

**Comment by steveoni** [comment]
it should not be so. I will check it out.

**Comment by steveoni** [comment]
the `new Intl.Collator` does not work well with negative values. might fall back to the normal sorting ways for numerical variables.
