### ISSUE TITLE
Comparing `!param` to `layout` always returns false.

### ISSUE THREAD

**Issue by hodovani** [opensource9ja/danfojs#77]
What is purpose of [this](https://github.com/opensource9ja/danfojs/blob/master/dist/plotting/plot.js#L30) line?

It return false if param is 'layout' or if it is any other string.

**Comment by risenW** [comment]
Ah thanks for spotting that. It actually caused a bug. That line is suppose to be  `if (!(param == "layout"))...`

**Comment by adithyaakrishna** [comment]
@risenW Is this specific error in this line? https://github.com/opensource9ja/danfojs/blob/master/danfojs-browser/src/plotting/plot.js#L48

Bc the link in the comment is giving 404 :/

**Comment by risenW** [comment]
> @risenW Is this specific error in this line? https://github.com/opensource9ja/danfojs/blob/master/danfojs-browser/src/plotting/plot.js#L48
> 
> Bc the link in the comment is giving 404 :/

It’s open for me. And yes, the error is on that line. I forgot to fix this. It’s a simple line change. 
Wanna do it?

**Comment by adithyaakrishna** [comment]
Yesss, Will Do 💯
