### ISSUE TITLE
Describe dataframe plot is missing the first column

### ISSUE THREAD

**Issue by ajainvivek** [opensource9ja/danfojs#82]
Dataframe describe plot is missing the first column `count, mean, deviation...`

`dataframe.describe().plot('plot-div').table()`

<img width="1409" alt="Screen Shot 2021-01-01 at 12 45 35 pm" src="https://user-images.githubusercontent.com/1182600/103432205-6fee6380-4c2f-11eb-9348-b00be8ef8ddd.png">

but print `dataframe.describe().print()` does have the static column

**Comment by risenW** [comment]
Thanks for pointing this out.
