### ISSUE TITLE
Browser example doesnt work

### ISSUE THREAD

**Issue by muneebshahid** [opensource9ja/danfojs#85]
[Browser example](https://github.com/opensource9ja/danfojs#example-usage-in-the-browser doesn't seen to work. It throws the error ``Uncaught ReferenceError: dfd is not defined`` 

I have to change version from 0.1.5 to 0.1.2 to get it to work.

``<script src="https://cdn.jsdelivr.net/npm/danfojs@0.1.5/dist/index.min.js"></script>``

to 

`` <script src="https://cdn.jsdelivr.net/npm/danfojs@0.1.2/dist/index.min.js"></script>``

**Comment by bebbi** [comment]
Try loading the script async and wait for it

```
function loadDanfojs() {
  return new Promise(resolve => {
    const existingScript = document.getElementById("danfojs")
    if (existingScript) {
      resolve()
      return
    }

    const script = document.createElement("script")
    script.src = "https://cdn.jsdelivr.net/npm/danfojs@0.1.5/dist/index.min.js"
    script.id = "danfojs"
    document.body.appendChild(script)
    script.onload = resolve
  })
}
```

**Comment by steveoni** [comment]
there is an issue with v0.1.5, we let you know about the next build.

**Comment by risenW** [comment]
@muneebshahid  just a quick update that this has been fixed. You can always get the latest version via the script tag `    <script src="https://cdn.jsdelivr.net/gh/opensource9ja/danfojs@latest/lib/bundle.js"></script>
``

**Comment by muneebshahid** [comment]
@risenW thank you for the quick fix and the update.
