### ISSUE TITLE
Disposing values

### ISSUE THREAD

**Issue by GantMan** [opensource9ja/danfojs#86]
When I'm done with a DataFrame, is there a proper way to dispose the dataframe and reclaim the tensor memory?

I haven't found anything.

**Comment by risenW** [comment]
Good catch. I’m planning a series of refactor for efficient  memory management and this will definitely be part of that. Any help here would definitely be appreciated as well

**Comment by GantMan** [comment]
In Panda s you can say `del df` to remove it from memory.   So should it be `df.del` or should you follow the TF way of things and say `df.dispose`?   I'm leaning towards dispose, or `dfd.del(df)`?

**Comment by risenW** [comment]
> In Panda s you can say `del df` to remove it from memory. So should it be `df.del` or should you follow the TF way of things and say `df.dispose`? I'm leaning towards dispose, or `dfd.del(df)`?

`df.dispose` seem better. I'll go with that. Wanna add this?

**Comment by GantMan** [comment]
I started setting up a codesandbox to work with this.  It appears danfo doesn't play well with codesandbox.com - you should probably add that to a list somewhere, too.

I'll have to make a local experiment and let you know if I think I can contribute this back or not.

**Comment by risenW** [comment]
@GantMan  I Fixed the sandbox issue as well. Check out this [example](https://codepen.io/risingodegua/pen/bGwPGMG)

**Comment by GantMan** [comment]
I'm glad the sandbox works. I still haven't found free time to come back and add dispose.  It's on the list of things to do :D
