### ISSUE TITLE
Local file upload in browser environment

### ISSUE THREAD

**Issue by Tathagatd96** [opensource9ja/danfojs#87]
@risenW is there a roadmap to including local file upload via a browser environment for danfo.js?

**Comment by steveoni** [comment]
This cool, but for now is not on the roadmap

**Comment by risenW** [comment]
> This cool, but for now is not on the roadmap

@steveoni This would be easy to implement, and I think is very useful. reopening this and adding a `first time` tag.

**Comment by risenW** [comment]
@steveoni I believe you fixed this already?

**Comment by steveoni** [comment]
yeah
