### ISSUE TITLE
dropna giving "file format not supported for now"

### ISSUE THREAD

**Issue by indy2005** [opensource9ja/danfojs#89]
let df_drop = df.dropna({axis:0})
index.min.js:9946 Uncaught File format not supported for now

This is the error I get when running the browser examples in the introduction.

Any advice appreciated.  {axis:1} works, but I want to do a row wise operation.

Stephen

**Comment by risenW** [comment]
> let df_drop = df.dropna({axis:0})
> index.min.js:9946 Uncaught File format not supported for now
> 
> This is the error I get when running the browser examples in the introduction.
> 
> Any advice appreciated. {axis:1} works, but I want to do a row wise operation.
> 
> Stephen

Can you provide one example that you tried here, and also which version are you working with?
