### ISSUE TITLE
Example of usage in the browser not working

### ISSUE THREAD

**Issue by sagoncalves** [opensource9ja/danfojs#90]
Hi i used this code example:

`    <script src="https://cdn.jsdelivr.net/npm/danfojs@0.1.5/dist/index.min.js"></script>
`

And get this error: 

<img width="531" alt="Screen Shot 2021-01-21 at 12 04 43 AM" src="https://user-images.githubusercontent.com/63732425/105274913-f803c100-5b7c-11eb-9b58-bd2019e1a9b4.png">

**Comment by risenW** [comment]
There’s an issue with version 0.1.5, can you use version 0.1.3 for now, I’m fixing this soon and will notify here.

**Comment by sagoncalves** [comment]
Thank you very much!

**Comment by risenW** [comment]
> Thank you very much!

@sagoncalves , just a quick update that this has been fixed. You can always get the latest version via the script tag `    <script src="https://cdn.jsdelivr.net/gh/opensource9ja/danfojs@latest/lib/bundle.js"></script>
`
