### ISSUE TITLE
Website down 

### ISSUE THREAD

**Issue by vxm5091** [opensource9ja/danfojs#94]
Hey Team - first off, thanks for putting this library together! My team and I have been getting up to speed on it over the last several days and it's been super helpful. Just wanted to give a quick heads up that your website has been down for the last day or so [https://danfo.jsdata.org/].  

Thanks again and enjoy the weekend! 
Vlad

**Comment by cimm** [comment]
Works for me. Might have been down before, I don't know but https://danfo.jsdata.org has been working fine the last 2 hours or so.

**Comment by steveoni** [comment]
oh, but it's working from my end. can you check again

**Comment by vxm5091** [comment]
Yep, just checked and works on my end too. Thanks!
