### ISSUE TITLE
Importing JSON datetime columns

### ISSUE THREAD

**Issue by cimm** [opensource9ja/danfojs#95]
New to Danfo, very clean and easy to work with, great job. :+1: I do have some problems understanding dates though.

In my JSON:

```json
[ { "recordedAt": "2017-02-16T00:00:00.000Z", "value": 300 }]
```
In my browser Danfo 0.1.2 script:

```js
df = new dfd.DataFrame(myJson)
df.ctypes.print()
```

The dtype for the `recordedAt` column is a `string`, this makes sense, JSON does not have dates. I tried appending columns where I convert the date string to a JavaScript date or a timestamp but since Danfo does not have a `datetime` dtype I can't explain Danfo the column data is representing a date. The examples all use date ranges but what if I already have dates in my input file?

Thanks!

**Comment by risenW** [comment]
@steveoni what do you think. Probably our date parser is not robust enough

**Comment by steveoni** [comment]
We don't have datetime as a `ctypes` or so. But the date parser is robust enough.

```js
myjson = [ { "recordedAt": "2017-02-16T00:00:00.000Z", "value": 300 }]
df = new dfd.DataFrame(myjson)

dateSeries = df["recordedAt"].dt

table(dateSeries.month_name())
```

**Comment by cimm** [comment]
I see. I didn't realize I had to call `dt` to convert the column to a date. I taught the `DateFrame` constructor would convert the values to dates internally.

```js
df = new dfd.DataFrame(myjson)
df.set_index({ key: "readAt", inplace: true })
df.plot("plot_div").line()
```

It works now!

**Comment by Svein-Tore** [comment]
> It looks like the info on this page is no longer accurate: https://danfo.jsdata.org/api-reference/general-functions/danfo.to_datetime
> 
> Following the example code with `toDateTime()` throws an error where as using `.dt` appears to works swimmingly.

Correct @chapmanderek ! I have the same experience!  The api reference seems to be is out of date.
