### ISSUE TITLE
sort_values on column with duplicate values

### ISSUE THREAD

**Issue by chengemily** [opensource9ja/danfojs#99]
When using `sort_values(by="colName")` where `colName` has duplicate values, only one unique row is represented per value in the final dataframe. For example let `df` be

Date  Name  Score
1/1    Alex     2
1/2    Bob     2

Then, `df.sort_values(by="Score")` gives

Date  Name  Score
1/1    Alex     2
1/1    Alex     2

The documentation is not clear on how to get around this issue by sorting by multiple columns.

**Comment by steveoni** [comment]
what version of danfo.js are you using?

**Comment by chengemily** [comment]
I'm using 0.1.1: <script src="https://cdn.jsdelivr.net/npm/danfojs@0.1.1/dist/index.min.js"></script>

**Comment by steveoni** [comment]
pls used the new update `@latest` or `0.1.2`. This issue is fixed in the latest version

**Comment by chengemily** [comment]
Great thanks! It works.
